/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AttractionTag implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long attractionId;
    private Long tagId;

    public AttractionTag() {}

    public AttractionTag(AttractionTag value) {
        this.attractionId = value.attractionId;
        this.tagId = value.tagId;
    }

    public AttractionTag(
        Long attractionId,
        Long tagId
    ) {
        this.attractionId = attractionId;
        this.tagId = tagId;
    }

    /**
     * Getter for <code>public.attraction_tag.attraction_id</code>.
     */
    public Long getAttractionId() {
        return this.attractionId;
    }

    /**
     * Setter for <code>public.attraction_tag.attraction_id</code>.
     */
    public void setAttractionId(Long attractionId) {
        this.attractionId = attractionId;
    }

    /**
     * Getter for <code>public.attraction_tag.tag_id</code>.
     */
    public Long getTagId() {
        return this.tagId;
    }

    /**
     * Setter for <code>public.attraction_tag.tag_id</code>.
     */
    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AttractionTag other = (AttractionTag) obj;
        if (this.attractionId == null) {
            if (other.attractionId != null)
                return false;
        }
        else if (!this.attractionId.equals(other.attractionId))
            return false;
        if (this.tagId == null) {
            if (other.tagId != null)
                return false;
        }
        else if (!this.tagId.equals(other.tagId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.attractionId == null) ? 0 : this.attractionId.hashCode());
        result = prime * result + ((this.tagId == null) ? 0 : this.tagId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AttractionTag (");

        sb.append(attractionId);
        sb.append(", ").append(tagId);

        sb.append(")");
        return sb.toString();
    }
}
