/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.pojos;


import ch.schlierelacht.admin.jooq.enums.ImageType;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AttractionImage implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long attractionId;
    private Long imageId;
    private ImageType type;

    public AttractionImage() {}

    public AttractionImage(AttractionImage value) {
        this.attractionId = value.attractionId;
        this.imageId = value.imageId;
        this.type = value.type;
    }

    public AttractionImage(
        Long attractionId,
        Long imageId,
        ImageType type
    ) {
        this.attractionId = attractionId;
        this.imageId = imageId;
        this.type = type;
    }

    /**
     * Getter for <code>public.attraction_image.attraction_id</code>.
     */
    public Long getAttractionId() {
        return this.attractionId;
    }

    /**
     * Setter for <code>public.attraction_image.attraction_id</code>.
     */
    public void setAttractionId(Long attractionId) {
        this.attractionId = attractionId;
    }

    /**
     * Getter for <code>public.attraction_image.image_id</code>.
     */
    public Long getImageId() {
        return this.imageId;
    }

    /**
     * Setter for <code>public.attraction_image.image_id</code>.
     */
    public void setImageId(Long imageId) {
        this.imageId = imageId;
    }

    /**
     * Getter for <code>public.attraction_image.type</code>.
     */
    public ImageType getType() {
        return this.type;
    }

    /**
     * Setter for <code>public.attraction_image.type</code>.
     */
    public void setType(ImageType type) {
        this.type = type;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AttractionImage other = (AttractionImage) obj;
        if (this.attractionId == null) {
            if (other.attractionId != null)
                return false;
        }
        else if (!this.attractionId.equals(other.attractionId))
            return false;
        if (this.imageId == null) {
            if (other.imageId != null)
                return false;
        }
        else if (!this.imageId.equals(other.imageId))
            return false;
        if (this.type == null) {
            if (other.type != null)
                return false;
        }
        else if (!this.type.equals(other.type))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.attractionId == null) ? 0 : this.attractionId.hashCode());
        result = prime * result + ((this.imageId == null) ? 0 : this.imageId.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AttractionImage (");

        sb.append(attractionId);
        sb.append(", ").append(imageId);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
