/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.pojos;


import ch.schlierelacht.admin.jooq.enums.AttractionType;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Attraction implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private AttractionType type;
    private String name;
    private String description;
    private String website;
    private String instagram;
    private String facebook;
    private String youtube;

    public Attraction() {}

    public Attraction(Attraction value) {
        this.id = value.id;
        this.type = value.type;
        this.name = value.name;
        this.description = value.description;
        this.website = value.website;
        this.instagram = value.instagram;
        this.facebook = value.facebook;
        this.youtube = value.youtube;
    }

    public Attraction(
        Long id,
        AttractionType type,
        String name,
        String description,
        String website,
        String instagram,
        String facebook,
        String youtube
    ) {
        this.id = id;
        this.type = type;
        this.name = name;
        this.description = description;
        this.website = website;
        this.instagram = instagram;
        this.facebook = facebook;
        this.youtube = youtube;
    }

    /**
     * Getter for <code>public.attraction.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.attraction.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.attraction.type</code>.
     */
    public AttractionType getType() {
        return this.type;
    }

    /**
     * Setter for <code>public.attraction.type</code>.
     */
    public void setType(AttractionType type) {
        this.type = type;
    }

    /**
     * Getter for <code>public.attraction.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.attraction.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.attraction.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>public.attraction.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>public.attraction.website</code>.
     */
    public String getWebsite() {
        return this.website;
    }

    /**
     * Setter for <code>public.attraction.website</code>.
     */
    public void setWebsite(String website) {
        this.website = website;
    }

    /**
     * Getter for <code>public.attraction.instagram</code>.
     */
    public String getInstagram() {
        return this.instagram;
    }

    /**
     * Setter for <code>public.attraction.instagram</code>.
     */
    public void setInstagram(String instagram) {
        this.instagram = instagram;
    }

    /**
     * Getter for <code>public.attraction.facebook</code>.
     */
    public String getFacebook() {
        return this.facebook;
    }

    /**
     * Setter for <code>public.attraction.facebook</code>.
     */
    public void setFacebook(String facebook) {
        this.facebook = facebook;
    }

    /**
     * Getter for <code>public.attraction.youtube</code>.
     */
    public String getYoutube() {
        return this.youtube;
    }

    /**
     * Setter for <code>public.attraction.youtube</code>.
     */
    public void setYoutube(String youtube) {
        this.youtube = youtube;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Attraction other = (Attraction) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.type == null) {
            if (other.type != null)
                return false;
        }
        else if (!this.type.equals(other.type))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.website == null) {
            if (other.website != null)
                return false;
        }
        else if (!this.website.equals(other.website))
            return false;
        if (this.instagram == null) {
            if (other.instagram != null)
                return false;
        }
        else if (!this.instagram.equals(other.instagram))
            return false;
        if (this.facebook == null) {
            if (other.facebook != null)
                return false;
        }
        else if (!this.facebook.equals(other.facebook))
            return false;
        if (this.youtube == null) {
            if (other.youtube != null)
                return false;
        }
        else if (!this.youtube.equals(other.youtube))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.website == null) ? 0 : this.website.hashCode());
        result = prime * result + ((this.instagram == null) ? 0 : this.instagram.hashCode());
        result = prime * result + ((this.facebook == null) ? 0 : this.facebook.hashCode());
        result = prime * result + ((this.youtube == null) ? 0 : this.youtube.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Attraction (");

        sb.append(id);
        sb.append(", ").append(type);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(website);
        sb.append(", ").append(instagram);
        sb.append(", ").append(facebook);
        sb.append(", ").append(youtube);

        sb.append(")");
        return sb.toString();
    }
}
