/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.pojos;


import ch.schlierelacht.admin.jooq.enums.DownloadCategory;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Arrays;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Download implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private LocalDateTime uploadedAt;
    private String uploadedBy;
    private String filename;
    private String filetype;
    private String description;
    private Long filesize;
    private DownloadCategory category;
    private byte[] fileData;

    public Download() {}

    public Download(Download value) {
        this.id = value.id;
        this.uploadedAt = value.uploadedAt;
        this.uploadedBy = value.uploadedBy;
        this.filename = value.filename;
        this.filetype = value.filetype;
        this.description = value.description;
        this.filesize = value.filesize;
        this.category = value.category;
        this.fileData = value.fileData;
    }

    public Download(
        Long id,
        LocalDateTime uploadedAt,
        String uploadedBy,
        String filename,
        String filetype,
        String description,
        Long filesize,
        DownloadCategory category,
        byte[] fileData
    ) {
        this.id = id;
        this.uploadedAt = uploadedAt;
        this.uploadedBy = uploadedBy;
        this.filename = filename;
        this.filetype = filetype;
        this.description = description;
        this.filesize = filesize;
        this.category = category;
        this.fileData = fileData;
    }

    /**
     * Getter for <code>public.download.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.download.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.download.uploaded_at</code>.
     */
    public LocalDateTime getUploadedAt() {
        return this.uploadedAt;
    }

    /**
     * Setter for <code>public.download.uploaded_at</code>.
     */
    public void setUploadedAt(LocalDateTime uploadedAt) {
        this.uploadedAt = uploadedAt;
    }

    /**
     * Getter for <code>public.download.uploaded_by</code>.
     */
    public String getUploadedBy() {
        return this.uploadedBy;
    }

    /**
     * Setter for <code>public.download.uploaded_by</code>.
     */
    public void setUploadedBy(String uploadedBy) {
        this.uploadedBy = uploadedBy;
    }

    /**
     * Getter for <code>public.download.filename</code>.
     */
    public String getFilename() {
        return this.filename;
    }

    /**
     * Setter for <code>public.download.filename</code>.
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * Getter for <code>public.download.filetype</code>.
     */
    public String getFiletype() {
        return this.filetype;
    }

    /**
     * Setter for <code>public.download.filetype</code>.
     */
    public void setFiletype(String filetype) {
        this.filetype = filetype;
    }

    /**
     * Getter for <code>public.download.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>public.download.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>public.download.filesize</code>.
     */
    public Long getFilesize() {
        return this.filesize;
    }

    /**
     * Setter for <code>public.download.filesize</code>.
     */
    public void setFilesize(Long filesize) {
        this.filesize = filesize;
    }

    /**
     * Getter for <code>public.download.category</code>.
     */
    public DownloadCategory getCategory() {
        return this.category;
    }

    /**
     * Setter for <code>public.download.category</code>.
     */
    public void setCategory(DownloadCategory category) {
        this.category = category;
    }

    /**
     * Getter for <code>public.download.file_data</code>.
     */
    public byte[] getFileData() {
        return this.fileData;
    }

    /**
     * Setter for <code>public.download.file_data</code>.
     */
    public void setFileData(byte[] fileData) {
        this.fileData = fileData;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Download other = (Download) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.uploadedAt == null) {
            if (other.uploadedAt != null)
                return false;
        }
        else if (!this.uploadedAt.equals(other.uploadedAt))
            return false;
        if (this.uploadedBy == null) {
            if (other.uploadedBy != null)
                return false;
        }
        else if (!this.uploadedBy.equals(other.uploadedBy))
            return false;
        if (this.filename == null) {
            if (other.filename != null)
                return false;
        }
        else if (!this.filename.equals(other.filename))
            return false;
        if (this.filetype == null) {
            if (other.filetype != null)
                return false;
        }
        else if (!this.filetype.equals(other.filetype))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.filesize == null) {
            if (other.filesize != null)
                return false;
        }
        else if (!this.filesize.equals(other.filesize))
            return false;
        if (this.category == null) {
            if (other.category != null)
                return false;
        }
        else if (!this.category.equals(other.category))
            return false;
        if (this.fileData == null) {
            if (other.fileData != null)
                return false;
        }
        else if (!Arrays.equals(this.fileData, other.fileData))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.uploadedAt == null) ? 0 : this.uploadedAt.hashCode());
        result = prime * result + ((this.uploadedBy == null) ? 0 : this.uploadedBy.hashCode());
        result = prime * result + ((this.filename == null) ? 0 : this.filename.hashCode());
        result = prime * result + ((this.filetype == null) ? 0 : this.filetype.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.filesize == null) ? 0 : this.filesize.hashCode());
        result = prime * result + ((this.category == null) ? 0 : this.category.hashCode());
        result = prime * result + ((this.fileData == null) ? 0 : Arrays.hashCode(this.fileData));
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Download (");

        sb.append(id);
        sb.append(", ").append(uploadedAt);
        sb.append(", ").append(uploadedBy);
        sb.append(", ").append(filename);
        sb.append(", ").append(filetype);
        sb.append(", ").append(description);
        sb.append(", ").append(filesize);
        sb.append(", ").append(category);
        sb.append(", ").append("[binary...]");

        sb.append(")");
        return sb.toString();
    }
}
