/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GalleryImage implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String category;
    private String cloudflareId;
    private LocalDateTime uploadedAt;
    private String uploadedBy;

    public GalleryImage() {}

    public GalleryImage(GalleryImage value) {
        this.id = value.id;
        this.category = value.category;
        this.cloudflareId = value.cloudflareId;
        this.uploadedAt = value.uploadedAt;
        this.uploadedBy = value.uploadedBy;
    }

    public GalleryImage(
        Long id,
        String category,
        String cloudflareId,
        LocalDateTime uploadedAt,
        String uploadedBy
    ) {
        this.id = id;
        this.category = category;
        this.cloudflareId = cloudflareId;
        this.uploadedAt = uploadedAt;
        this.uploadedBy = uploadedBy;
    }

    /**
     * Getter for <code>public.gallery_image.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.gallery_image.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.gallery_image.category</code>.
     */
    public String getCategory() {
        return this.category;
    }

    /**
     * Setter for <code>public.gallery_image.category</code>.
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * Getter for <code>public.gallery_image.cloudflare_id</code>.
     */
    public String getCloudflareId() {
        return this.cloudflareId;
    }

    /**
     * Setter for <code>public.gallery_image.cloudflare_id</code>.
     */
    public void setCloudflareId(String cloudflareId) {
        this.cloudflareId = cloudflareId;
    }

    /**
     * Getter for <code>public.gallery_image.uploaded_at</code>.
     */
    public LocalDateTime getUploadedAt() {
        return this.uploadedAt;
    }

    /**
     * Setter for <code>public.gallery_image.uploaded_at</code>.
     */
    public void setUploadedAt(LocalDateTime uploadedAt) {
        this.uploadedAt = uploadedAt;
    }

    /**
     * Getter for <code>public.gallery_image.uploaded_by</code>.
     */
    public String getUploadedBy() {
        return this.uploadedBy;
    }

    /**
     * Setter for <code>public.gallery_image.uploaded_by</code>.
     */
    public void setUploadedBy(String uploadedBy) {
        this.uploadedBy = uploadedBy;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final GalleryImage other = (GalleryImage) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.category == null) {
            if (other.category != null)
                return false;
        }
        else if (!this.category.equals(other.category))
            return false;
        if (this.cloudflareId == null) {
            if (other.cloudflareId != null)
                return false;
        }
        else if (!this.cloudflareId.equals(other.cloudflareId))
            return false;
        if (this.uploadedAt == null) {
            if (other.uploadedAt != null)
                return false;
        }
        else if (!this.uploadedAt.equals(other.uploadedAt))
            return false;
        if (this.uploadedBy == null) {
            if (other.uploadedBy != null)
                return false;
        }
        else if (!this.uploadedBy.equals(other.uploadedBy))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.category == null) ? 0 : this.category.hashCode());
        result = prime * result + ((this.cloudflareId == null) ? 0 : this.cloudflareId.hashCode());
        result = prime * result + ((this.uploadedAt == null) ? 0 : this.uploadedAt.hashCode());
        result = prime * result + ((this.uploadedBy == null) ? 0 : this.uploadedBy.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GalleryImage (");

        sb.append(id);
        sb.append(", ").append(category);
        sb.append(", ").append(cloudflareId);
        sb.append(", ").append(uploadedAt);
        sb.append(", ").append(uploadedBy);

        sb.append(")");
        return sb.toString();
    }
}
