/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GalleryCategory implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String name;
    private Integer sortOrder;

    public GalleryCategory() {}

    public GalleryCategory(GalleryCategory value) {
        this.id = value.id;
        this.name = value.name;
        this.sortOrder = value.sortOrder;
    }

    public GalleryCategory(
        Long id,
        String name,
        Integer sortOrder
    ) {
        this.id = id;
        this.name = name;
        this.sortOrder = sortOrder;
    }

    /**
     * Getter for <code>public.gallery_category.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.gallery_category.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.gallery_category.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.gallery_category.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.gallery_category.sort_order</code>.
     */
    public Integer getSortOrder() {
        return this.sortOrder;
    }

    /**
     * Setter for <code>public.gallery_category.sort_order</code>.
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final GalleryCategory other = (GalleryCategory) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.sortOrder == null) {
            if (other.sortOrder != null)
                return false;
        }
        else if (!this.sortOrder.equals(other.sortOrder))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.sortOrder == null) ? 0 : this.sortOrder.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GalleryCategory (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(sortOrder);

        sb.append(")");
        return sb.toString();
    }
}
