/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Image implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String cloudflareId;
    private String description;
    private Integer width;
    private Integer height;

    public Image() {}

    public Image(Image value) {
        this.id = value.id;
        this.cloudflareId = value.cloudflareId;
        this.description = value.description;
        this.width = value.width;
        this.height = value.height;
    }

    public Image(
        Long id,
        String cloudflareId,
        String description,
        Integer width,
        Integer height
    ) {
        this.id = id;
        this.cloudflareId = cloudflareId;
        this.description = description;
        this.width = width;
        this.height = height;
    }

    /**
     * Getter for <code>public.image.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.image.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.image.cloudflare_id</code>.
     */
    public String getCloudflareId() {
        return this.cloudflareId;
    }

    /**
     * Setter for <code>public.image.cloudflare_id</code>.
     */
    public void setCloudflareId(String cloudflareId) {
        this.cloudflareId = cloudflareId;
    }

    /**
     * Getter for <code>public.image.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>public.image.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>public.image.width</code>.
     */
    public Integer getWidth() {
        return this.width;
    }

    /**
     * Setter for <code>public.image.width</code>.
     */
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * Getter for <code>public.image.height</code>.
     */
    public Integer getHeight() {
        return this.height;
    }

    /**
     * Setter for <code>public.image.height</code>.
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Image other = (Image) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.cloudflareId == null) {
            if (other.cloudflareId != null)
                return false;
        }
        else if (!this.cloudflareId.equals(other.cloudflareId))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.width == null) {
            if (other.width != null)
                return false;
        }
        else if (!this.width.equals(other.width))
            return false;
        if (this.height == null) {
            if (other.height != null)
                return false;
        }
        else if (!this.height.equals(other.height))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.cloudflareId == null) ? 0 : this.cloudflareId.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.width == null) ? 0 : this.width.hashCode());
        result = prime * result + ((this.height == null) ? 0 : this.height.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Image (");

        sb.append(id);
        sb.append(", ").append(cloudflareId);
        sb.append(", ").append(description);
        sb.append(", ").append(width);
        sb.append(", ").append(height);

        sb.append(")");
        return sb.toString();
    }
}
