/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.pojos;


import ch.schlierelacht.admin.jooq.enums.LocationType;

import java.io.Serializable;
import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Location implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String externalId;
    private LocationType type;
    private String name;
    private BigDecimal latitude;
    private BigDecimal longitude;
    private Integer sortOrder;
    private String cloudflareId;
    private String mapId;

    public Location() {}

    public Location(Location value) {
        this.id = value.id;
        this.externalId = value.externalId;
        this.type = value.type;
        this.name = value.name;
        this.latitude = value.latitude;
        this.longitude = value.longitude;
        this.sortOrder = value.sortOrder;
        this.cloudflareId = value.cloudflareId;
        this.mapId = value.mapId;
    }

    public Location(
        Long id,
        String externalId,
        LocationType type,
        String name,
        BigDecimal latitude,
        BigDecimal longitude,
        Integer sortOrder,
        String cloudflareId,
        String mapId
    ) {
        this.id = id;
        this.externalId = externalId;
        this.type = type;
        this.name = name;
        this.latitude = latitude;
        this.longitude = longitude;
        this.sortOrder = sortOrder;
        this.cloudflareId = cloudflareId;
        this.mapId = mapId;
    }

    /**
     * Getter for <code>public.location.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.location.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.location.external_id</code>.
     */
    public String getExternalId() {
        return this.externalId;
    }

    /**
     * Setter for <code>public.location.external_id</code>.
     */
    public void setExternalId(String externalId) {
        this.externalId = externalId;
    }

    /**
     * Getter for <code>public.location.type</code>.
     */
    public LocationType getType() {
        return this.type;
    }

    /**
     * Setter for <code>public.location.type</code>.
     */
    public void setType(LocationType type) {
        this.type = type;
    }

    /**
     * Getter for <code>public.location.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.location.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.location.latitude</code>.
     */
    public BigDecimal getLatitude() {
        return this.latitude;
    }

    /**
     * Setter for <code>public.location.latitude</code>.
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * Getter for <code>public.location.longitude</code>.
     */
    public BigDecimal getLongitude() {
        return this.longitude;
    }

    /**
     * Setter for <code>public.location.longitude</code>.
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * Getter for <code>public.location.sort_order</code>.
     */
    public Integer getSortOrder() {
        return this.sortOrder;
    }

    /**
     * Setter for <code>public.location.sort_order</code>.
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * Getter for <code>public.location.cloudflare_id</code>.
     */
    public String getCloudflareId() {
        return this.cloudflareId;
    }

    /**
     * Setter for <code>public.location.cloudflare_id</code>.
     */
    public void setCloudflareId(String cloudflareId) {
        this.cloudflareId = cloudflareId;
    }

    /**
     * Getter for <code>public.location.map_id</code>.
     */
    public String getMapId() {
        return this.mapId;
    }

    /**
     * Setter for <code>public.location.map_id</code>.
     */
    public void setMapId(String mapId) {
        this.mapId = mapId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Location other = (Location) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.externalId == null) {
            if (other.externalId != null)
                return false;
        }
        else if (!this.externalId.equals(other.externalId))
            return false;
        if (this.type == null) {
            if (other.type != null)
                return false;
        }
        else if (!this.type.equals(other.type))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.latitude == null) {
            if (other.latitude != null)
                return false;
        }
        else if (!this.latitude.equals(other.latitude))
            return false;
        if (this.longitude == null) {
            if (other.longitude != null)
                return false;
        }
        else if (!this.longitude.equals(other.longitude))
            return false;
        if (this.sortOrder == null) {
            if (other.sortOrder != null)
                return false;
        }
        else if (!this.sortOrder.equals(other.sortOrder))
            return false;
        if (this.cloudflareId == null) {
            if (other.cloudflareId != null)
                return false;
        }
        else if (!this.cloudflareId.equals(other.cloudflareId))
            return false;
        if (this.mapId == null) {
            if (other.mapId != null)
                return false;
        }
        else if (!this.mapId.equals(other.mapId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.externalId == null) ? 0 : this.externalId.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.latitude == null) ? 0 : this.latitude.hashCode());
        result = prime * result + ((this.longitude == null) ? 0 : this.longitude.hashCode());
        result = prime * result + ((this.sortOrder == null) ? 0 : this.sortOrder.hashCode());
        result = prime * result + ((this.cloudflareId == null) ? 0 : this.cloudflareId.hashCode());
        result = prime * result + ((this.mapId == null) ? 0 : this.mapId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Location (");

        sb.append(id);
        sb.append(", ").append(externalId);
        sb.append(", ").append(type);
        sb.append(", ").append(name);
        sb.append(", ").append(latitude);
        sb.append(", ").append(longitude);
        sb.append(", ").append(sortOrder);
        sb.append(", ").append(cloudflareId);
        sb.append(", ").append(mapId);

        sb.append(")");
        return sb.toString();
    }
}
