/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.pojos;


import ch.schlierelacht.admin.jooq.enums.MeetupJahrgang;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MeetupRegistration implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private LocalDateTime registeredAt;
    private String firstname;
    private String lastname;
    private String email;
    private MeetupJahrgang jahrgang;
    private Boolean showOnList;

    public MeetupRegistration() {}

    public MeetupRegistration(MeetupRegistration value) {
        this.id = value.id;
        this.registeredAt = value.registeredAt;
        this.firstname = value.firstname;
        this.lastname = value.lastname;
        this.email = value.email;
        this.jahrgang = value.jahrgang;
        this.showOnList = value.showOnList;
    }

    public MeetupRegistration(
        Long id,
        LocalDateTime registeredAt,
        String firstname,
        String lastname,
        String email,
        MeetupJahrgang jahrgang,
        Boolean showOnList
    ) {
        this.id = id;
        this.registeredAt = registeredAt;
        this.firstname = firstname;
        this.lastname = lastname;
        this.email = email;
        this.jahrgang = jahrgang;
        this.showOnList = showOnList;
    }

    /**
     * Getter for <code>public.meetup_registration.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.meetup_registration.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.meetup_registration.registered_at</code>.
     */
    public LocalDateTime getRegisteredAt() {
        return this.registeredAt;
    }

    /**
     * Setter for <code>public.meetup_registration.registered_at</code>.
     */
    public void setRegisteredAt(LocalDateTime registeredAt) {
        this.registeredAt = registeredAt;
    }

    /**
     * Getter for <code>public.meetup_registration.firstname</code>.
     */
    public String getFirstname() {
        return this.firstname;
    }

    /**
     * Setter for <code>public.meetup_registration.firstname</code>.
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    /**
     * Getter for <code>public.meetup_registration.lastname</code>.
     */
    public String getLastname() {
        return this.lastname;
    }

    /**
     * Setter for <code>public.meetup_registration.lastname</code>.
     */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    /**
     * Getter for <code>public.meetup_registration.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>public.meetup_registration.email</code>.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>public.meetup_registration.jahrgang</code>.
     */
    public MeetupJahrgang getJahrgang() {
        return this.jahrgang;
    }

    /**
     * Setter for <code>public.meetup_registration.jahrgang</code>.
     */
    public void setJahrgang(MeetupJahrgang jahrgang) {
        this.jahrgang = jahrgang;
    }

    /**
     * Getter for <code>public.meetup_registration.show_on_list</code>.
     */
    public Boolean getShowOnList() {
        return this.showOnList;
    }

    /**
     * Setter for <code>public.meetup_registration.show_on_list</code>.
     */
    public void setShowOnList(Boolean showOnList) {
        this.showOnList = showOnList;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final MeetupRegistration other = (MeetupRegistration) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.registeredAt == null) {
            if (other.registeredAt != null)
                return false;
        }
        else if (!this.registeredAt.equals(other.registeredAt))
            return false;
        if (this.firstname == null) {
            if (other.firstname != null)
                return false;
        }
        else if (!this.firstname.equals(other.firstname))
            return false;
        if (this.lastname == null) {
            if (other.lastname != null)
                return false;
        }
        else if (!this.lastname.equals(other.lastname))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.jahrgang == null) {
            if (other.jahrgang != null)
                return false;
        }
        else if (!this.jahrgang.equals(other.jahrgang))
            return false;
        if (this.showOnList == null) {
            if (other.showOnList != null)
                return false;
        }
        else if (!this.showOnList.equals(other.showOnList))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.registeredAt == null) ? 0 : this.registeredAt.hashCode());
        result = prime * result + ((this.firstname == null) ? 0 : this.firstname.hashCode());
        result = prime * result + ((this.lastname == null) ? 0 : this.lastname.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.jahrgang == null) ? 0 : this.jahrgang.hashCode());
        result = prime * result + ((this.showOnList == null) ? 0 : this.showOnList.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MeetupRegistration (");

        sb.append(id);
        sb.append(", ").append(registeredAt);
        sb.append(", ").append(firstname);
        sb.append(", ").append(lastname);
        sb.append(", ").append(email);
        sb.append(", ").append(jahrgang);
        sb.append(", ").append(showOnList);

        sb.append(")");
        return sb.toString();
    }
}
