/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class News implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private LocalDate date;
    private String title;
    private String introText;
    private String fullText;
    private String cloudflareId;
    private Boolean active;

    public News() {}

    public News(News value) {
        this.id = value.id;
        this.date = value.date;
        this.title = value.title;
        this.introText = value.introText;
        this.fullText = value.fullText;
        this.cloudflareId = value.cloudflareId;
        this.active = value.active;
    }

    public News(
        Long id,
        LocalDate date,
        String title,
        String introText,
        String fullText,
        String cloudflareId,
        Boolean active
    ) {
        this.id = id;
        this.date = date;
        this.title = title;
        this.introText = introText;
        this.fullText = fullText;
        this.cloudflareId = cloudflareId;
        this.active = active;
    }

    /**
     * Getter for <code>public.news.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.news.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.news.date</code>.
     */
    public LocalDate getDate() {
        return this.date;
    }

    /**
     * Setter for <code>public.news.date</code>.
     */
    public void setDate(LocalDate date) {
        this.date = date;
    }

    /**
     * Getter for <code>public.news.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>public.news.title</code>.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>public.news.intro_text</code>.
     */
    public String getIntroText() {
        return this.introText;
    }

    /**
     * Setter for <code>public.news.intro_text</code>.
     */
    public void setIntroText(String introText) {
        this.introText = introText;
    }

    /**
     * Getter for <code>public.news.full_text</code>.
     */
    public String getFullText() {
        return this.fullText;
    }

    /**
     * Setter for <code>public.news.full_text</code>.
     */
    public void setFullText(String fullText) {
        this.fullText = fullText;
    }

    /**
     * Getter for <code>public.news.cloudflare_id</code>.
     */
    public String getCloudflareId() {
        return this.cloudflareId;
    }

    /**
     * Setter for <code>public.news.cloudflare_id</code>.
     */
    public void setCloudflareId(String cloudflareId) {
        this.cloudflareId = cloudflareId;
    }

    /**
     * Getter for <code>public.news.active</code>.
     */
    public Boolean getActive() {
        return this.active;
    }

    /**
     * Setter for <code>public.news.active</code>.
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final News other = (News) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.date == null) {
            if (other.date != null)
                return false;
        }
        else if (!this.date.equals(other.date))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.introText == null) {
            if (other.introText != null)
                return false;
        }
        else if (!this.introText.equals(other.introText))
            return false;
        if (this.fullText == null) {
            if (other.fullText != null)
                return false;
        }
        else if (!this.fullText.equals(other.fullText))
            return false;
        if (this.cloudflareId == null) {
            if (other.cloudflareId != null)
                return false;
        }
        else if (!this.cloudflareId.equals(other.cloudflareId))
            return false;
        if (this.active == null) {
            if (other.active != null)
                return false;
        }
        else if (!this.active.equals(other.active))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.date == null) ? 0 : this.date.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.introText == null) ? 0 : this.introText.hashCode());
        result = prime * result + ((this.fullText == null) ? 0 : this.fullText.hashCode());
        result = prime * result + ((this.cloudflareId == null) ? 0 : this.cloudflareId.hashCode());
        result = prime * result + ((this.active == null) ? 0 : this.active.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("News (");

        sb.append(id);
        sb.append(", ").append(date);
        sb.append(", ").append(title);
        sb.append(", ").append(introText);
        sb.append(", ").append(fullText);
        sb.append(", ").append(cloudflareId);
        sb.append(", ").append(active);

        sb.append(")");
        return sb.toString();
    }
}
