/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OkMember implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String name;
    private String role;
    private String email;
    private String cloudflareId;
    private Integer sortOrder;

    public OkMember() {}

    public OkMember(OkMember value) {
        this.id = value.id;
        this.name = value.name;
        this.role = value.role;
        this.email = value.email;
        this.cloudflareId = value.cloudflareId;
        this.sortOrder = value.sortOrder;
    }

    public OkMember(
        Long id,
        String name,
        String role,
        String email,
        String cloudflareId,
        Integer sortOrder
    ) {
        this.id = id;
        this.name = name;
        this.role = role;
        this.email = email;
        this.cloudflareId = cloudflareId;
        this.sortOrder = sortOrder;
    }

    /**
     * Getter for <code>public.ok_member.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.ok_member.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.ok_member.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.ok_member.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.ok_member.role</code>.
     */
    public String getRole() {
        return this.role;
    }

    /**
     * Setter for <code>public.ok_member.role</code>.
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * Getter for <code>public.ok_member.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>public.ok_member.email</code>.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>public.ok_member.cloudflare_id</code>.
     */
    public String getCloudflareId() {
        return this.cloudflareId;
    }

    /**
     * Setter for <code>public.ok_member.cloudflare_id</code>.
     */
    public void setCloudflareId(String cloudflareId) {
        this.cloudflareId = cloudflareId;
    }

    /**
     * Getter for <code>public.ok_member.sort_order</code>.
     */
    public Integer getSortOrder() {
        return this.sortOrder;
    }

    /**
     * Setter for <code>public.ok_member.sort_order</code>.
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OkMember other = (OkMember) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.role == null) {
            if (other.role != null)
                return false;
        }
        else if (!this.role.equals(other.role))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.cloudflareId == null) {
            if (other.cloudflareId != null)
                return false;
        }
        else if (!this.cloudflareId.equals(other.cloudflareId))
            return false;
        if (this.sortOrder == null) {
            if (other.sortOrder != null)
                return false;
        }
        else if (!this.sortOrder.equals(other.sortOrder))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.role == null) ? 0 : this.role.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.cloudflareId == null) ? 0 : this.cloudflareId.hashCode());
        result = prime * result + ((this.sortOrder == null) ? 0 : this.sortOrder.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OkMember (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(role);
        sb.append(", ").append(email);
        sb.append(", ").append(cloudflareId);
        sb.append(", ").append(sortOrder);

        sb.append(")");
        return sb.toString();
    }
}
