/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.pojos;


import ch.schlierelacht.admin.jooq.enums.OkTeam;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OkTeamMember implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String name;
    private OkTeam team;
    private String email;

    public OkTeamMember() {}

    public OkTeamMember(OkTeamMember value) {
        this.id = value.id;
        this.name = value.name;
        this.team = value.team;
        this.email = value.email;
    }

    public OkTeamMember(
        Long id,
        String name,
        OkTeam team,
        String email
    ) {
        this.id = id;
        this.name = name;
        this.team = team;
        this.email = email;
    }

    /**
     * Getter for <code>public.ok_team_member.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.ok_team_member.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.ok_team_member.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.ok_team_member.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.ok_team_member.team</code>.
     */
    public OkTeam getTeam() {
        return this.team;
    }

    /**
     * Setter for <code>public.ok_team_member.team</code>.
     */
    public void setTeam(OkTeam team) {
        this.team = team;
    }

    /**
     * Getter for <code>public.ok_team_member.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>public.ok_team_member.email</code>.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OkTeamMember other = (OkTeamMember) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.team == null) {
            if (other.team != null)
                return false;
        }
        else if (!this.team.equals(other.team))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.team == null) ? 0 : this.team.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OkTeamMember (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(team);
        sb.append(", ").append(email);

        sb.append(")");
        return sb.toString();
    }
}
