/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Programm implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long attractionId;
    private Long locationId;
    private LocalDate fromDate;
    private LocalTime fromTime;
    private LocalDate toDate;
    private LocalTime toTime;

    public Programm() {}

    public Programm(Programm value) {
        this.id = value.id;
        this.attractionId = value.attractionId;
        this.locationId = value.locationId;
        this.fromDate = value.fromDate;
        this.fromTime = value.fromTime;
        this.toDate = value.toDate;
        this.toTime = value.toTime;
    }

    public Programm(
        Long id,
        Long attractionId,
        Long locationId,
        LocalDate fromDate,
        LocalTime fromTime,
        LocalDate toDate,
        LocalTime toTime
    ) {
        this.id = id;
        this.attractionId = attractionId;
        this.locationId = locationId;
        this.fromDate = fromDate;
        this.fromTime = fromTime;
        this.toDate = toDate;
        this.toTime = toTime;
    }

    /**
     * Getter for <code>public.programm.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.programm.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.programm.attraction_id</code>.
     */
    public Long getAttractionId() {
        return this.attractionId;
    }

    /**
     * Setter for <code>public.programm.attraction_id</code>.
     */
    public void setAttractionId(Long attractionId) {
        this.attractionId = attractionId;
    }

    /**
     * Getter for <code>public.programm.location_id</code>.
     */
    public Long getLocationId() {
        return this.locationId;
    }

    /**
     * Setter for <code>public.programm.location_id</code>.
     */
    public void setLocationId(Long locationId) {
        this.locationId = locationId;
    }

    /**
     * Getter for <code>public.programm.from_date</code>.
     */
    public LocalDate getFromDate() {
        return this.fromDate;
    }

    /**
     * Setter for <code>public.programm.from_date</code>.
     */
    public void setFromDate(LocalDate fromDate) {
        this.fromDate = fromDate;
    }

    /**
     * Getter for <code>public.programm.from_time</code>.
     */
    public LocalTime getFromTime() {
        return this.fromTime;
    }

    /**
     * Setter for <code>public.programm.from_time</code>.
     */
    public void setFromTime(LocalTime fromTime) {
        this.fromTime = fromTime;
    }

    /**
     * Getter for <code>public.programm.to_date</code>.
     */
    public LocalDate getToDate() {
        return this.toDate;
    }

    /**
     * Setter for <code>public.programm.to_date</code>.
     */
    public void setToDate(LocalDate toDate) {
        this.toDate = toDate;
    }

    /**
     * Getter for <code>public.programm.to_time</code>.
     */
    public LocalTime getToTime() {
        return this.toTime;
    }

    /**
     * Setter for <code>public.programm.to_time</code>.
     */
    public void setToTime(LocalTime toTime) {
        this.toTime = toTime;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Programm other = (Programm) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.attractionId == null) {
            if (other.attractionId != null)
                return false;
        }
        else if (!this.attractionId.equals(other.attractionId))
            return false;
        if (this.locationId == null) {
            if (other.locationId != null)
                return false;
        }
        else if (!this.locationId.equals(other.locationId))
            return false;
        if (this.fromDate == null) {
            if (other.fromDate != null)
                return false;
        }
        else if (!this.fromDate.equals(other.fromDate))
            return false;
        if (this.fromTime == null) {
            if (other.fromTime != null)
                return false;
        }
        else if (!this.fromTime.equals(other.fromTime))
            return false;
        if (this.toDate == null) {
            if (other.toDate != null)
                return false;
        }
        else if (!this.toDate.equals(other.toDate))
            return false;
        if (this.toTime == null) {
            if (other.toTime != null)
                return false;
        }
        else if (!this.toTime.equals(other.toTime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.attractionId == null) ? 0 : this.attractionId.hashCode());
        result = prime * result + ((this.locationId == null) ? 0 : this.locationId.hashCode());
        result = prime * result + ((this.fromDate == null) ? 0 : this.fromDate.hashCode());
        result = prime * result + ((this.fromTime == null) ? 0 : this.fromTime.hashCode());
        result = prime * result + ((this.toDate == null) ? 0 : this.toDate.hashCode());
        result = prime * result + ((this.toTime == null) ? 0 : this.toTime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Programm (");

        sb.append(id);
        sb.append(", ").append(attractionId);
        sb.append(", ").append(locationId);
        sb.append(", ").append(fromDate);
        sb.append(", ").append(fromTime);
        sb.append(", ").append(toDate);
        sb.append(", ").append(toTime);

        sb.append(")");
        return sb.toString();
    }
}
