/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PushDeviceToken implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String token;
    private String platform;
    private String locale;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public PushDeviceToken() {}

    public PushDeviceToken(PushDeviceToken value) {
        this.id = value.id;
        this.token = value.token;
        this.platform = value.platform;
        this.locale = value.locale;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public PushDeviceToken(
        Long id,
        String token,
        String platform,
        String locale,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.token = token;
        this.platform = platform;
        this.locale = locale;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.push_device_token.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.push_device_token.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.push_device_token.token</code>.
     */
    public String getToken() {
        return this.token;
    }

    /**
     * Setter for <code>public.push_device_token.token</code>.
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * Getter for <code>public.push_device_token.platform</code>.
     */
    public String getPlatform() {
        return this.platform;
    }

    /**
     * Setter for <code>public.push_device_token.platform</code>.
     */
    public void setPlatform(String platform) {
        this.platform = platform;
    }

    /**
     * Getter for <code>public.push_device_token.locale</code>.
     */
    public String getLocale() {
        return this.locale;
    }

    /**
     * Setter for <code>public.push_device_token.locale</code>.
     */
    public void setLocale(String locale) {
        this.locale = locale;
    }

    /**
     * Getter for <code>public.push_device_token.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.push_device_token.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.push_device_token.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.push_device_token.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PushDeviceToken other = (PushDeviceToken) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.token == null) {
            if (other.token != null)
                return false;
        }
        else if (!this.token.equals(other.token))
            return false;
        if (this.platform == null) {
            if (other.platform != null)
                return false;
        }
        else if (!this.platform.equals(other.platform))
            return false;
        if (this.locale == null) {
            if (other.locale != null)
                return false;
        }
        else if (!this.locale.equals(other.locale))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.token == null) ? 0 : this.token.hashCode());
        result = prime * result + ((this.platform == null) ? 0 : this.platform.hashCode());
        result = prime * result + ((this.locale == null) ? 0 : this.locale.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PushDeviceToken (");

        sb.append(id);
        sb.append(", ").append(token);
        sb.append(", ").append(platform);
        sb.append(", ").append(locale);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
