/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.pojos;


import ch.schlierelacht.admin.jooq.enums.SponsoringType;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sponsoring implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private SponsoringType type;
    private String name;
    private String cloudflareId;
    private String url;

    public Sponsoring() {}

    public Sponsoring(Sponsoring value) {
        this.id = value.id;
        this.type = value.type;
        this.name = value.name;
        this.cloudflareId = value.cloudflareId;
        this.url = value.url;
    }

    public Sponsoring(
        Long id,
        SponsoringType type,
        String name,
        String cloudflareId,
        String url
    ) {
        this.id = id;
        this.type = type;
        this.name = name;
        this.cloudflareId = cloudflareId;
        this.url = url;
    }

    /**
     * Getter for <code>public.sponsoring.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.sponsoring.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.sponsoring.type</code>.
     */
    public SponsoringType getType() {
        return this.type;
    }

    /**
     * Setter for <code>public.sponsoring.type</code>.
     */
    public void setType(SponsoringType type) {
        this.type = type;
    }

    /**
     * Getter for <code>public.sponsoring.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.sponsoring.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.sponsoring.cloudflare_id</code>.
     */
    public String getCloudflareId() {
        return this.cloudflareId;
    }

    /**
     * Setter for <code>public.sponsoring.cloudflare_id</code>.
     */
    public void setCloudflareId(String cloudflareId) {
        this.cloudflareId = cloudflareId;
    }

    /**
     * Getter for <code>public.sponsoring.url</code>.
     */
    public String getUrl() {
        return this.url;
    }

    /**
     * Setter for <code>public.sponsoring.url</code>.
     */
    public void setUrl(String url) {
        this.url = url;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Sponsoring other = (Sponsoring) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.type == null) {
            if (other.type != null)
                return false;
        }
        else if (!this.type.equals(other.type))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.cloudflareId == null) {
            if (other.cloudflareId != null)
                return false;
        }
        else if (!this.cloudflareId.equals(other.cloudflareId))
            return false;
        if (this.url == null) {
            if (other.url != null)
                return false;
        }
        else if (!this.url.equals(other.url))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.cloudflareId == null) ? 0 : this.cloudflareId.hashCode());
        result = prime * result + ((this.url == null) ? 0 : this.url.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Sponsoring (");

        sb.append(id);
        sb.append(", ").append(type);
        sb.append(", ").append(name);
        sb.append(", ").append(cloudflareId);
        sb.append(", ").append(url);

        sb.append(")");
        return sb.toString();
    }
}
