/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.pojos;


import ch.schlierelacht.admin.jooq.enums.AttractionType;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tag implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String name;
    private AttractionType type;

    public Tag() {}

    public Tag(Tag value) {
        this.id = value.id;
        this.name = value.name;
        this.type = value.type;
    }

    public Tag(
        Long id,
        String name,
        AttractionType type
    ) {
        this.id = id;
        this.name = name;
        this.type = type;
    }

    /**
     * Getter for <code>public.tag.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.tag.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.tag.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.tag.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.tag.type</code>.
     */
    public AttractionType getType() {
        return this.type;
    }

    /**
     * Setter for <code>public.tag.type</code>.
     */
    public void setType(AttractionType type) {
        this.type = type;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Tag other = (Tag) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.type == null) {
            if (other.type != null)
                return false;
        }
        else if (!this.type.equals(other.type))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Tag (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
