
app.cloudflare-account-id        = ${CLOUDFLARE_ACCOUNT_ID}
# https://developers.cloudflare.com/fundamentals/api/get-started/create-token/
app.cloudflare-api-token         = ${CLOUDFLARE_API_TOKEN}
app.cloudflare-base-url          = https://api.cloudflare.com/client/v4
app.cloudflare-imagedelivery-url = https://imagedelivery.net/08WjJu0y_NwzY_GFS74XCw
app.meetup-notification-email    = ${MEETUP_NOTIFICATION_EMAIL}
# https://mjml.io/api
app.mjml.application-id          = ${MJML_APPLICATION_ID}
app.mjml.secret-key              = ${MJML_SECRET_KEY}
app.remember-me-key              = ${REMEMBER_ME_KEY}

logging.level.org.atmosphere = warn
logging.mail.host            = ${LOGGING_MAIL_HOST}
logging.mail.password        = ${LOGGING_MAIL_PASSWORD}
logging.mail.port            = ${LOGGING_MAIL_PORT:587}
logging.mail.to              = ${LOGGING_MAIL_TO}
logging.mail.user            = ${LOGGING_MAIL_USER}

management.endpoint.health.show-details   = never
management.endpoints.web.exposure.include = health,info
management.info.env.enabled               = true

server.port = ${PORT:8080}

spring.datasource.password                       = ${SPRING_DATASOURCE_PASSWORD}
spring.datasource.url                            = ${SPRING_DATASOURCE_URL}
spring.datasource.username                       = ${SPRING_DATASOURCE_USERNAME}
spring.mail.host                                 = ${MAIL_HOST}
spring.mail.password                             = ${MAIL_PASSWORD}
spring.mail.port                                 = ${MAIL_PORT:587}
spring.mail.properties.mail.smtp.auth            = true
spring.mail.properties.mail.smtp.starttls.enable = true
spring.mail.username                             = ${MAIL_USERNAME}
spring.servlet.multipart.max-file-size           = 100MB
spring.servlet.multipart.max-request-size        = 100MB

vaadin.allowed-packages = com.vaadin,org.vaadin,com.flowingcode,ch.schlierelacht
vaadin.exclude-urls     = /api/**
vaadin.launch-browser   = true
