/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.daos;


import ch.schlierelacht.admin.jooq.AbstractSpringDAOImpl;
import ch.schlierelacht.admin.jooq.tables.AttractionFile;
import ch.schlierelacht.admin.jooq.tables.records.AttractionFileRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class AttractionFileDao extends AbstractSpringDAOImpl<AttractionFileRecord, ch.schlierelacht.admin.jooq.tables.pojos.AttractionFile, Long> {

    /**
     * Create a new AttractionFileDao without any configuration
     */
    public AttractionFileDao() {
        super(AttractionFile.ATTRACTION_FILE, ch.schlierelacht.admin.jooq.tables.pojos.AttractionFile.class);
    }

    /**
     * Create a new AttractionFileDao with an attached configuration
     */
    @Autowired
    public AttractionFileDao(Configuration configuration) {
        super(AttractionFile.ATTRACTION_FILE, ch.schlierelacht.admin.jooq.tables.pojos.AttractionFile.class, configuration);
    }

    @Override
    public Long getId(ch.schlierelacht.admin.jooq.tables.pojos.AttractionFile object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.AttractionFile> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(AttractionFile.ATTRACTION_FILE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.AttractionFile> fetchById(Long... values) {
        return fetch(AttractionFile.ATTRACTION_FILE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ch.schlierelacht.admin.jooq.tables.pojos.AttractionFile fetchOneById(Long value) {
        return fetchOne(AttractionFile.ATTRACTION_FILE.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<ch.schlierelacht.admin.jooq.tables.pojos.AttractionFile> fetchOptionalById(Long value) {
        return fetchOptional(AttractionFile.ATTRACTION_FILE.ID, value);
    }

    /**
     * Fetch records that have <code>attraction_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.AttractionFile> fetchRangeOfAttractionId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(AttractionFile.ATTRACTION_FILE.ATTRACTION_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>attraction_id IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.AttractionFile> fetchByAttractionId(Long... values) {
        return fetch(AttractionFile.ATTRACTION_FILE.ATTRACTION_ID, values);
    }

    /**
     * Fetch records that have <code>filename BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.AttractionFile> fetchRangeOfFilename(String lowerInclusive, String upperInclusive) {
        return fetchRange(AttractionFile.ATTRACTION_FILE.FILENAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>filename IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.AttractionFile> fetchByFilename(String... values) {
        return fetch(AttractionFile.ATTRACTION_FILE.FILENAME, values);
    }

    /**
     * Fetch records that have <code>filetype BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.AttractionFile> fetchRangeOfFiletype(String lowerInclusive, String upperInclusive) {
        return fetchRange(AttractionFile.ATTRACTION_FILE.FILETYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>filetype IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.AttractionFile> fetchByFiletype(String... values) {
        return fetch(AttractionFile.ATTRACTION_FILE.FILETYPE, values);
    }

    /**
     * Fetch records that have <code>description BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.AttractionFile> fetchRangeOfDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(AttractionFile.ATTRACTION_FILE.DESCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.AttractionFile> fetchByDescription(String... values) {
        return fetch(AttractionFile.ATTRACTION_FILE.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>filesize BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.AttractionFile> fetchRangeOfFilesize(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(AttractionFile.ATTRACTION_FILE.FILESIZE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>filesize IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.AttractionFile> fetchByFilesize(Long... values) {
        return fetch(AttractionFile.ATTRACTION_FILE.FILESIZE, values);
    }

    /**
     * Fetch records that have <code>file_data BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.AttractionFile> fetchRangeOfFileData(byte[] lowerInclusive, byte[] upperInclusive) {
        return fetchRange(AttractionFile.ATTRACTION_FILE.FILE_DATA, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>file_data IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.AttractionFile> fetchByFileData(byte[]... values) {
        return fetch(AttractionFile.ATTRACTION_FILE.FILE_DATA, values);
    }

    /**
     * Fetch records that have <code>uploaded_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.AttractionFile> fetchRangeOfUploadedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(AttractionFile.ATTRACTION_FILE.UPLOADED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>uploaded_at IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.AttractionFile> fetchByUploadedAt(LocalDateTime... values) {
        return fetch(AttractionFile.ATTRACTION_FILE.UPLOADED_AT, values);
    }

    /**
     * Fetch records that have <code>uploaded_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.AttractionFile> fetchRangeOfUploadedBy(String lowerInclusive, String upperInclusive) {
        return fetchRange(AttractionFile.ATTRACTION_FILE.UPLOADED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>uploaded_by IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.AttractionFile> fetchByUploadedBy(String... values) {
        return fetch(AttractionFile.ATTRACTION_FILE.UPLOADED_BY, values);
    }
}
