/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.daos;


import ch.schlierelacht.admin.jooq.AbstractSpringDAOImpl;
import ch.schlierelacht.admin.jooq.enums.AttractionType;
import ch.schlierelacht.admin.jooq.tables.Attraction;
import ch.schlierelacht.admin.jooq.tables.records.AttractionRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class AttractionDao extends AbstractSpringDAOImpl<AttractionRecord, ch.schlierelacht.admin.jooq.tables.pojos.Attraction, Long> {

    /**
     * Create a new AttractionDao without any configuration
     */
    public AttractionDao() {
        super(Attraction.ATTRACTION, ch.schlierelacht.admin.jooq.tables.pojos.Attraction.class);
    }

    /**
     * Create a new AttractionDao with an attached configuration
     */
    @Autowired
    public AttractionDao(Configuration configuration) {
        super(Attraction.ATTRACTION, ch.schlierelacht.admin.jooq.tables.pojos.Attraction.class, configuration);
    }

    @Override
    public Long getId(ch.schlierelacht.admin.jooq.tables.pojos.Attraction object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Attraction> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Attraction.ATTRACTION.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Attraction> fetchById(Long... values) {
        return fetch(Attraction.ATTRACTION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ch.schlierelacht.admin.jooq.tables.pojos.Attraction fetchOneById(Long value) {
        return fetchOne(Attraction.ATTRACTION.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<ch.schlierelacht.admin.jooq.tables.pojos.Attraction> fetchOptionalById(Long value) {
        return fetchOptional(Attraction.ATTRACTION.ID, value);
    }

    /**
     * Fetch records that have <code>type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Attraction> fetchRangeOfType(AttractionType lowerInclusive, AttractionType upperInclusive) {
        return fetchRange(Attraction.ATTRACTION.TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Attraction> fetchByType(AttractionType... values) {
        return fetch(Attraction.ATTRACTION.TYPE, values);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Attraction> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Attraction.ATTRACTION.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Attraction> fetchByName(String... values) {
        return fetch(Attraction.ATTRACTION.NAME, values);
    }

    /**
     * Fetch records that have <code>description BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Attraction> fetchRangeOfDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(Attraction.ATTRACTION.DESCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Attraction> fetchByDescription(String... values) {
        return fetch(Attraction.ATTRACTION.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>website BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Attraction> fetchRangeOfWebsite(String lowerInclusive, String upperInclusive) {
        return fetchRange(Attraction.ATTRACTION.WEBSITE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>website IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Attraction> fetchByWebsite(String... values) {
        return fetch(Attraction.ATTRACTION.WEBSITE, values);
    }

    /**
     * Fetch records that have <code>instagram BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Attraction> fetchRangeOfInstagram(String lowerInclusive, String upperInclusive) {
        return fetchRange(Attraction.ATTRACTION.INSTAGRAM, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>instagram IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Attraction> fetchByInstagram(String... values) {
        return fetch(Attraction.ATTRACTION.INSTAGRAM, values);
    }

    /**
     * Fetch records that have <code>facebook BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Attraction> fetchRangeOfFacebook(String lowerInclusive, String upperInclusive) {
        return fetchRange(Attraction.ATTRACTION.FACEBOOK, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>facebook IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Attraction> fetchByFacebook(String... values) {
        return fetch(Attraction.ATTRACTION.FACEBOOK, values);
    }

    /**
     * Fetch records that have <code>youtube BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Attraction> fetchRangeOfYoutube(String lowerInclusive, String upperInclusive) {
        return fetchRange(Attraction.ATTRACTION.YOUTUBE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>youtube IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Attraction> fetchByYoutube(String... values) {
        return fetch(Attraction.ATTRACTION.YOUTUBE, values);
    }
}
