/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.daos;


import ch.schlierelacht.admin.jooq.AbstractSpringDAOImpl;
import ch.schlierelacht.admin.jooq.tables.AttractionTag;
import ch.schlierelacht.admin.jooq.tables.records.AttractionTagRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class AttractionTagDao extends AbstractSpringDAOImpl<AttractionTagRecord, ch.schlierelacht.admin.jooq.tables.pojos.AttractionTag, Record2<Long, Long>> {

    /**
     * Create a new AttractionTagDao without any configuration
     */
    public AttractionTagDao() {
        super(AttractionTag.ATTRACTION_TAG, ch.schlierelacht.admin.jooq.tables.pojos.AttractionTag.class);
    }

    /**
     * Create a new AttractionTagDao with an attached configuration
     */
    @Autowired
    public AttractionTagDao(Configuration configuration) {
        super(AttractionTag.ATTRACTION_TAG, ch.schlierelacht.admin.jooq.tables.pojos.AttractionTag.class, configuration);
    }

    @Override
    public Record2<Long, Long> getId(ch.schlierelacht.admin.jooq.tables.pojos.AttractionTag object) {
        return compositeKeyRecord(object.getAttractionId(), object.getTagId());
    }

    /**
     * Fetch records that have <code>attraction_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.AttractionTag> fetchRangeOfAttractionId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(AttractionTag.ATTRACTION_TAG.ATTRACTION_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>attraction_id IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.AttractionTag> fetchByAttractionId(Long... values) {
        return fetch(AttractionTag.ATTRACTION_TAG.ATTRACTION_ID, values);
    }

    /**
     * Fetch records that have <code>tag_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.AttractionTag> fetchRangeOfTagId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(AttractionTag.ATTRACTION_TAG.TAG_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>tag_id IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.AttractionTag> fetchByTagId(Long... values) {
        return fetch(AttractionTag.ATTRACTION_TAG.TAG_ID, values);
    }
}
