/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.daos;


import ch.schlierelacht.admin.jooq.AbstractSpringDAOImpl;
import ch.schlierelacht.admin.jooq.enums.DownloadCategory;
import ch.schlierelacht.admin.jooq.tables.Download;
import ch.schlierelacht.admin.jooq.tables.records.DownloadRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class DownloadDao extends AbstractSpringDAOImpl<DownloadRecord, ch.schlierelacht.admin.jooq.tables.pojos.Download, Long> {

    /**
     * Create a new DownloadDao without any configuration
     */
    public DownloadDao() {
        super(Download.DOWNLOAD, ch.schlierelacht.admin.jooq.tables.pojos.Download.class);
    }

    /**
     * Create a new DownloadDao with an attached configuration
     */
    @Autowired
    public DownloadDao(Configuration configuration) {
        super(Download.DOWNLOAD, ch.schlierelacht.admin.jooq.tables.pojos.Download.class, configuration);
    }

    @Override
    public Long getId(ch.schlierelacht.admin.jooq.tables.pojos.Download object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Download> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Download.DOWNLOAD.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Download> fetchById(Long... values) {
        return fetch(Download.DOWNLOAD.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ch.schlierelacht.admin.jooq.tables.pojos.Download fetchOneById(Long value) {
        return fetchOne(Download.DOWNLOAD.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<ch.schlierelacht.admin.jooq.tables.pojos.Download> fetchOptionalById(Long value) {
        return fetchOptional(Download.DOWNLOAD.ID, value);
    }

    /**
     * Fetch records that have <code>uploaded_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Download> fetchRangeOfUploadedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Download.DOWNLOAD.UPLOADED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>uploaded_at IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Download> fetchByUploadedAt(LocalDateTime... values) {
        return fetch(Download.DOWNLOAD.UPLOADED_AT, values);
    }

    /**
     * Fetch records that have <code>uploaded_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Download> fetchRangeOfUploadedBy(String lowerInclusive, String upperInclusive) {
        return fetchRange(Download.DOWNLOAD.UPLOADED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>uploaded_by IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Download> fetchByUploadedBy(String... values) {
        return fetch(Download.DOWNLOAD.UPLOADED_BY, values);
    }

    /**
     * Fetch records that have <code>filename BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Download> fetchRangeOfFilename(String lowerInclusive, String upperInclusive) {
        return fetchRange(Download.DOWNLOAD.FILENAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>filename IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Download> fetchByFilename(String... values) {
        return fetch(Download.DOWNLOAD.FILENAME, values);
    }

    /**
     * Fetch records that have <code>filetype BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Download> fetchRangeOfFiletype(String lowerInclusive, String upperInclusive) {
        return fetchRange(Download.DOWNLOAD.FILETYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>filetype IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Download> fetchByFiletype(String... values) {
        return fetch(Download.DOWNLOAD.FILETYPE, values);
    }

    /**
     * Fetch records that have <code>description BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Download> fetchRangeOfDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(Download.DOWNLOAD.DESCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Download> fetchByDescription(String... values) {
        return fetch(Download.DOWNLOAD.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>filesize BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Download> fetchRangeOfFilesize(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Download.DOWNLOAD.FILESIZE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>filesize IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Download> fetchByFilesize(Long... values) {
        return fetch(Download.DOWNLOAD.FILESIZE, values);
    }

    /**
     * Fetch records that have <code>category BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Download> fetchRangeOfCategory(DownloadCategory lowerInclusive, DownloadCategory upperInclusive) {
        return fetchRange(Download.DOWNLOAD.CATEGORY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>category IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Download> fetchByCategory(DownloadCategory... values) {
        return fetch(Download.DOWNLOAD.CATEGORY, values);
    }

    /**
     * Fetch records that have <code>file_data BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Download> fetchRangeOfFileData(byte[] lowerInclusive, byte[] upperInclusive) {
        return fetchRange(Download.DOWNLOAD.FILE_DATA, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>file_data IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Download> fetchByFileData(byte[]... values) {
        return fetch(Download.DOWNLOAD.FILE_DATA, values);
    }
}
