/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.daos;


import ch.schlierelacht.admin.jooq.AbstractSpringDAOImpl;
import ch.schlierelacht.admin.jooq.tables.GalleryCategory;
import ch.schlierelacht.admin.jooq.tables.records.GalleryCategoryRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class GalleryCategoryDao extends AbstractSpringDAOImpl<GalleryCategoryRecord, ch.schlierelacht.admin.jooq.tables.pojos.GalleryCategory, Long> {

    /**
     * Create a new GalleryCategoryDao without any configuration
     */
    public GalleryCategoryDao() {
        super(GalleryCategory.GALLERY_CATEGORY, ch.schlierelacht.admin.jooq.tables.pojos.GalleryCategory.class);
    }

    /**
     * Create a new GalleryCategoryDao with an attached configuration
     */
    @Autowired
    public GalleryCategoryDao(Configuration configuration) {
        super(GalleryCategory.GALLERY_CATEGORY, ch.schlierelacht.admin.jooq.tables.pojos.GalleryCategory.class, configuration);
    }

    @Override
    public Long getId(ch.schlierelacht.admin.jooq.tables.pojos.GalleryCategory object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.GalleryCategory> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(GalleryCategory.GALLERY_CATEGORY.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.GalleryCategory> fetchById(Long... values) {
        return fetch(GalleryCategory.GALLERY_CATEGORY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ch.schlierelacht.admin.jooq.tables.pojos.GalleryCategory fetchOneById(Long value) {
        return fetchOne(GalleryCategory.GALLERY_CATEGORY.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<ch.schlierelacht.admin.jooq.tables.pojos.GalleryCategory> fetchOptionalById(Long value) {
        return fetchOptional(GalleryCategory.GALLERY_CATEGORY.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.GalleryCategory> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(GalleryCategory.GALLERY_CATEGORY.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.GalleryCategory> fetchByName(String... values) {
        return fetch(GalleryCategory.GALLERY_CATEGORY.NAME, values);
    }

    /**
     * Fetch a unique record that has <code>name = value</code>
     */
    public ch.schlierelacht.admin.jooq.tables.pojos.GalleryCategory fetchOneByName(String value) {
        return fetchOne(GalleryCategory.GALLERY_CATEGORY.NAME, value);
    }

    /**
     * Fetch a unique record that has <code>name = value</code>
     */
    public Optional<ch.schlierelacht.admin.jooq.tables.pojos.GalleryCategory> fetchOptionalByName(String value) {
        return fetchOptional(GalleryCategory.GALLERY_CATEGORY.NAME, value);
    }

    /**
     * Fetch records that have <code>sort_order BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.GalleryCategory> fetchRangeOfSortOrder(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(GalleryCategory.GALLERY_CATEGORY.SORT_ORDER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>sort_order IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.GalleryCategory> fetchBySortOrder(Integer... values) {
        return fetch(GalleryCategory.GALLERY_CATEGORY.SORT_ORDER, values);
    }
}
