/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.daos;


import ch.schlierelacht.admin.jooq.AbstractSpringDAOImpl;
import ch.schlierelacht.admin.jooq.tables.GalleryImage;
import ch.schlierelacht.admin.jooq.tables.records.GalleryImageRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class GalleryImageDao extends AbstractSpringDAOImpl<GalleryImageRecord, ch.schlierelacht.admin.jooq.tables.pojos.GalleryImage, Long> {

    /**
     * Create a new GalleryImageDao without any configuration
     */
    public GalleryImageDao() {
        super(GalleryImage.GALLERY_IMAGE, ch.schlierelacht.admin.jooq.tables.pojos.GalleryImage.class);
    }

    /**
     * Create a new GalleryImageDao with an attached configuration
     */
    @Autowired
    public GalleryImageDao(Configuration configuration) {
        super(GalleryImage.GALLERY_IMAGE, ch.schlierelacht.admin.jooq.tables.pojos.GalleryImage.class, configuration);
    }

    @Override
    public Long getId(ch.schlierelacht.admin.jooq.tables.pojos.GalleryImage object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.GalleryImage> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(GalleryImage.GALLERY_IMAGE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.GalleryImage> fetchById(Long... values) {
        return fetch(GalleryImage.GALLERY_IMAGE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ch.schlierelacht.admin.jooq.tables.pojos.GalleryImage fetchOneById(Long value) {
        return fetchOne(GalleryImage.GALLERY_IMAGE.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<ch.schlierelacht.admin.jooq.tables.pojos.GalleryImage> fetchOptionalById(Long value) {
        return fetchOptional(GalleryImage.GALLERY_IMAGE.ID, value);
    }

    /**
     * Fetch records that have <code>category BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.GalleryImage> fetchRangeOfCategory(String lowerInclusive, String upperInclusive) {
        return fetchRange(GalleryImage.GALLERY_IMAGE.CATEGORY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>category IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.GalleryImage> fetchByCategory(String... values) {
        return fetch(GalleryImage.GALLERY_IMAGE.CATEGORY, values);
    }

    /**
     * Fetch records that have <code>cloudflare_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.GalleryImage> fetchRangeOfCloudflareId(String lowerInclusive, String upperInclusive) {
        return fetchRange(GalleryImage.GALLERY_IMAGE.CLOUDFLARE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>cloudflare_id IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.GalleryImage> fetchByCloudflareId(String... values) {
        return fetch(GalleryImage.GALLERY_IMAGE.CLOUDFLARE_ID, values);
    }

    /**
     * Fetch records that have <code>uploaded_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.GalleryImage> fetchRangeOfUploadedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(GalleryImage.GALLERY_IMAGE.UPLOADED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>uploaded_at IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.GalleryImage> fetchByUploadedAt(LocalDateTime... values) {
        return fetch(GalleryImage.GALLERY_IMAGE.UPLOADED_AT, values);
    }

    /**
     * Fetch records that have <code>uploaded_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.GalleryImage> fetchRangeOfUploadedBy(String lowerInclusive, String upperInclusive) {
        return fetchRange(GalleryImage.GALLERY_IMAGE.UPLOADED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>uploaded_by IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.GalleryImage> fetchByUploadedBy(String... values) {
        return fetch(GalleryImage.GALLERY_IMAGE.UPLOADED_BY, values);
    }
}
