/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.daos;


import ch.schlierelacht.admin.jooq.AbstractSpringDAOImpl;
import ch.schlierelacht.admin.jooq.tables.Image;
import ch.schlierelacht.admin.jooq.tables.records.ImageRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class ImageDao extends AbstractSpringDAOImpl<ImageRecord, ch.schlierelacht.admin.jooq.tables.pojos.Image, Long> {

    /**
     * Create a new ImageDao without any configuration
     */
    public ImageDao() {
        super(Image.IMAGE, ch.schlierelacht.admin.jooq.tables.pojos.Image.class);
    }

    /**
     * Create a new ImageDao with an attached configuration
     */
    @Autowired
    public ImageDao(Configuration configuration) {
        super(Image.IMAGE, ch.schlierelacht.admin.jooq.tables.pojos.Image.class, configuration);
    }

    @Override
    public Long getId(ch.schlierelacht.admin.jooq.tables.pojos.Image object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Image> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Image.IMAGE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Image> fetchById(Long... values) {
        return fetch(Image.IMAGE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ch.schlierelacht.admin.jooq.tables.pojos.Image fetchOneById(Long value) {
        return fetchOne(Image.IMAGE.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<ch.schlierelacht.admin.jooq.tables.pojos.Image> fetchOptionalById(Long value) {
        return fetchOptional(Image.IMAGE.ID, value);
    }

    /**
     * Fetch records that have <code>cloudflare_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Image> fetchRangeOfCloudflareId(String lowerInclusive, String upperInclusive) {
        return fetchRange(Image.IMAGE.CLOUDFLARE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>cloudflare_id IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Image> fetchByCloudflareId(String... values) {
        return fetch(Image.IMAGE.CLOUDFLARE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>cloudflare_id = value</code>
     */
    public ch.schlierelacht.admin.jooq.tables.pojos.Image fetchOneByCloudflareId(String value) {
        return fetchOne(Image.IMAGE.CLOUDFLARE_ID, value);
    }

    /**
     * Fetch a unique record that has <code>cloudflare_id = value</code>
     */
    public Optional<ch.schlierelacht.admin.jooq.tables.pojos.Image> fetchOptionalByCloudflareId(String value) {
        return fetchOptional(Image.IMAGE.CLOUDFLARE_ID, value);
    }

    /**
     * Fetch records that have <code>description BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Image> fetchRangeOfDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(Image.IMAGE.DESCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Image> fetchByDescription(String... values) {
        return fetch(Image.IMAGE.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>width BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Image> fetchRangeOfWidth(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Image.IMAGE.WIDTH, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>width IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Image> fetchByWidth(Integer... values) {
        return fetch(Image.IMAGE.WIDTH, values);
    }

    /**
     * Fetch records that have <code>height BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Image> fetchRangeOfHeight(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Image.IMAGE.HEIGHT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>height IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Image> fetchByHeight(Integer... values) {
        return fetch(Image.IMAGE.HEIGHT, values);
    }
}
