/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.daos;


import ch.schlierelacht.admin.jooq.AbstractSpringDAOImpl;
import ch.schlierelacht.admin.jooq.enums.LocationType;
import ch.schlierelacht.admin.jooq.tables.Location;
import ch.schlierelacht.admin.jooq.tables.records.LocationRecord;

import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class LocationDao extends AbstractSpringDAOImpl<LocationRecord, ch.schlierelacht.admin.jooq.tables.pojos.Location, Long> {

    /**
     * Create a new LocationDao without any configuration
     */
    public LocationDao() {
        super(Location.LOCATION, ch.schlierelacht.admin.jooq.tables.pojos.Location.class);
    }

    /**
     * Create a new LocationDao with an attached configuration
     */
    @Autowired
    public LocationDao(Configuration configuration) {
        super(Location.LOCATION, ch.schlierelacht.admin.jooq.tables.pojos.Location.class, configuration);
    }

    @Override
    public Long getId(ch.schlierelacht.admin.jooq.tables.pojos.Location object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Location> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Location.LOCATION.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Location> fetchById(Long... values) {
        return fetch(Location.LOCATION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ch.schlierelacht.admin.jooq.tables.pojos.Location fetchOneById(Long value) {
        return fetchOne(Location.LOCATION.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<ch.schlierelacht.admin.jooq.tables.pojos.Location> fetchOptionalById(Long value) {
        return fetchOptional(Location.LOCATION.ID, value);
    }

    /**
     * Fetch records that have <code>external_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Location> fetchRangeOfExternalId(String lowerInclusive, String upperInclusive) {
        return fetchRange(Location.LOCATION.EXTERNAL_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>external_id IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Location> fetchByExternalId(String... values) {
        return fetch(Location.LOCATION.EXTERNAL_ID, values);
    }

    /**
     * Fetch a unique record that has <code>external_id = value</code>
     */
    public ch.schlierelacht.admin.jooq.tables.pojos.Location fetchOneByExternalId(String value) {
        return fetchOne(Location.LOCATION.EXTERNAL_ID, value);
    }

    /**
     * Fetch a unique record that has <code>external_id = value</code>
     */
    public Optional<ch.schlierelacht.admin.jooq.tables.pojos.Location> fetchOptionalByExternalId(String value) {
        return fetchOptional(Location.LOCATION.EXTERNAL_ID, value);
    }

    /**
     * Fetch records that have <code>type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Location> fetchRangeOfType(LocationType lowerInclusive, LocationType upperInclusive) {
        return fetchRange(Location.LOCATION.TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Location> fetchByType(LocationType... values) {
        return fetch(Location.LOCATION.TYPE, values);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Location> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Location.LOCATION.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Location> fetchByName(String... values) {
        return fetch(Location.LOCATION.NAME, values);
    }

    /**
     * Fetch records that have <code>latitude BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Location> fetchRangeOfLatitude(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(Location.LOCATION.LATITUDE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>latitude IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Location> fetchByLatitude(BigDecimal... values) {
        return fetch(Location.LOCATION.LATITUDE, values);
    }

    /**
     * Fetch records that have <code>longitude BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Location> fetchRangeOfLongitude(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(Location.LOCATION.LONGITUDE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>longitude IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Location> fetchByLongitude(BigDecimal... values) {
        return fetch(Location.LOCATION.LONGITUDE, values);
    }

    /**
     * Fetch records that have <code>sort_order BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Location> fetchRangeOfSortOrder(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Location.LOCATION.SORT_ORDER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>sort_order IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Location> fetchBySortOrder(Integer... values) {
        return fetch(Location.LOCATION.SORT_ORDER, values);
    }

    /**
     * Fetch records that have <code>cloudflare_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Location> fetchRangeOfCloudflareId(String lowerInclusive, String upperInclusive) {
        return fetchRange(Location.LOCATION.CLOUDFLARE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>cloudflare_id IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Location> fetchByCloudflareId(String... values) {
        return fetch(Location.LOCATION.CLOUDFLARE_ID, values);
    }

    /**
     * Fetch records that have <code>map_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Location> fetchRangeOfMapId(String lowerInclusive, String upperInclusive) {
        return fetchRange(Location.LOCATION.MAP_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>map_id IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Location> fetchByMapId(String... values) {
        return fetch(Location.LOCATION.MAP_ID, values);
    }
}
