/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.daos;


import ch.schlierelacht.admin.jooq.AbstractSpringDAOImpl;
import ch.schlierelacht.admin.jooq.enums.MeetupJahrgang;
import ch.schlierelacht.admin.jooq.tables.MeetupRegistration;
import ch.schlierelacht.admin.jooq.tables.records.MeetupRegistrationRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class MeetupRegistrationDao extends AbstractSpringDAOImpl<MeetupRegistrationRecord, ch.schlierelacht.admin.jooq.tables.pojos.MeetupRegistration, Long> {

    /**
     * Create a new MeetupRegistrationDao without any configuration
     */
    public MeetupRegistrationDao() {
        super(MeetupRegistration.MEETUP_REGISTRATION, ch.schlierelacht.admin.jooq.tables.pojos.MeetupRegistration.class);
    }

    /**
     * Create a new MeetupRegistrationDao with an attached configuration
     */
    @Autowired
    public MeetupRegistrationDao(Configuration configuration) {
        super(MeetupRegistration.MEETUP_REGISTRATION, ch.schlierelacht.admin.jooq.tables.pojos.MeetupRegistration.class, configuration);
    }

    @Override
    public Long getId(ch.schlierelacht.admin.jooq.tables.pojos.MeetupRegistration object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.MeetupRegistration> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(MeetupRegistration.MEETUP_REGISTRATION.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.MeetupRegistration> fetchById(Long... values) {
        return fetch(MeetupRegistration.MEETUP_REGISTRATION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ch.schlierelacht.admin.jooq.tables.pojos.MeetupRegistration fetchOneById(Long value) {
        return fetchOne(MeetupRegistration.MEETUP_REGISTRATION.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<ch.schlierelacht.admin.jooq.tables.pojos.MeetupRegistration> fetchOptionalById(Long value) {
        return fetchOptional(MeetupRegistration.MEETUP_REGISTRATION.ID, value);
    }

    /**
     * Fetch records that have <code>registered_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.MeetupRegistration> fetchRangeOfRegisteredAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(MeetupRegistration.MEETUP_REGISTRATION.REGISTERED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>registered_at IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.MeetupRegistration> fetchByRegisteredAt(LocalDateTime... values) {
        return fetch(MeetupRegistration.MEETUP_REGISTRATION.REGISTERED_AT, values);
    }

    /**
     * Fetch records that have <code>firstname BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.MeetupRegistration> fetchRangeOfFirstname(String lowerInclusive, String upperInclusive) {
        return fetchRange(MeetupRegistration.MEETUP_REGISTRATION.FIRSTNAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>firstname IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.MeetupRegistration> fetchByFirstname(String... values) {
        return fetch(MeetupRegistration.MEETUP_REGISTRATION.FIRSTNAME, values);
    }

    /**
     * Fetch records that have <code>lastname BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.MeetupRegistration> fetchRangeOfLastname(String lowerInclusive, String upperInclusive) {
        return fetchRange(MeetupRegistration.MEETUP_REGISTRATION.LASTNAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>lastname IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.MeetupRegistration> fetchByLastname(String... values) {
        return fetch(MeetupRegistration.MEETUP_REGISTRATION.LASTNAME, values);
    }

    /**
     * Fetch records that have <code>email BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.MeetupRegistration> fetchRangeOfEmail(String lowerInclusive, String upperInclusive) {
        return fetchRange(MeetupRegistration.MEETUP_REGISTRATION.EMAIL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.MeetupRegistration> fetchByEmail(String... values) {
        return fetch(MeetupRegistration.MEETUP_REGISTRATION.EMAIL, values);
    }

    /**
     * Fetch records that have <code>jahrgang BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.MeetupRegistration> fetchRangeOfJahrgang(MeetupJahrgang lowerInclusive, MeetupJahrgang upperInclusive) {
        return fetchRange(MeetupRegistration.MEETUP_REGISTRATION.JAHRGANG, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>jahrgang IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.MeetupRegistration> fetchByJahrgang(MeetupJahrgang... values) {
        return fetch(MeetupRegistration.MEETUP_REGISTRATION.JAHRGANG, values);
    }

    /**
     * Fetch records that have <code>show_on_list BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.MeetupRegistration> fetchRangeOfShowOnList(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(MeetupRegistration.MEETUP_REGISTRATION.SHOW_ON_LIST, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>show_on_list IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.MeetupRegistration> fetchByShowOnList(Boolean... values) {
        return fetch(MeetupRegistration.MEETUP_REGISTRATION.SHOW_ON_LIST, values);
    }
}
