/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.daos;


import ch.schlierelacht.admin.jooq.AbstractSpringDAOImpl;
import ch.schlierelacht.admin.jooq.tables.News;
import ch.schlierelacht.admin.jooq.tables.records.NewsRecord;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class NewsDao extends AbstractSpringDAOImpl<NewsRecord, ch.schlierelacht.admin.jooq.tables.pojos.News, Long> {

    /**
     * Create a new NewsDao without any configuration
     */
    public NewsDao() {
        super(News.NEWS, ch.schlierelacht.admin.jooq.tables.pojos.News.class);
    }

    /**
     * Create a new NewsDao with an attached configuration
     */
    @Autowired
    public NewsDao(Configuration configuration) {
        super(News.NEWS, ch.schlierelacht.admin.jooq.tables.pojos.News.class, configuration);
    }

    @Override
    public Long getId(ch.schlierelacht.admin.jooq.tables.pojos.News object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.News> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(News.NEWS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.News> fetchById(Long... values) {
        return fetch(News.NEWS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ch.schlierelacht.admin.jooq.tables.pojos.News fetchOneById(Long value) {
        return fetchOne(News.NEWS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<ch.schlierelacht.admin.jooq.tables.pojos.News> fetchOptionalById(Long value) {
        return fetchOptional(News.NEWS.ID, value);
    }

    /**
     * Fetch records that have <code>date BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.News> fetchRangeOfDate(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(News.NEWS.DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>date IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.News> fetchByDate(LocalDate... values) {
        return fetch(News.NEWS.DATE, values);
    }

    /**
     * Fetch records that have <code>title BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.News> fetchRangeOfTitle(String lowerInclusive, String upperInclusive) {
        return fetchRange(News.NEWS.TITLE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.News> fetchByTitle(String... values) {
        return fetch(News.NEWS.TITLE, values);
    }

    /**
     * Fetch records that have <code>intro_text BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.News> fetchRangeOfIntroText(String lowerInclusive, String upperInclusive) {
        return fetchRange(News.NEWS.INTRO_TEXT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>intro_text IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.News> fetchByIntroText(String... values) {
        return fetch(News.NEWS.INTRO_TEXT, values);
    }

    /**
     * Fetch records that have <code>full_text BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.News> fetchRangeOfFullText(String lowerInclusive, String upperInclusive) {
        return fetchRange(News.NEWS.FULL_TEXT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>full_text IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.News> fetchByFullText(String... values) {
        return fetch(News.NEWS.FULL_TEXT, values);
    }

    /**
     * Fetch records that have <code>cloudflare_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.News> fetchRangeOfCloudflareId(String lowerInclusive, String upperInclusive) {
        return fetchRange(News.NEWS.CLOUDFLARE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>cloudflare_id IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.News> fetchByCloudflareId(String... values) {
        return fetch(News.NEWS.CLOUDFLARE_ID, values);
    }

    /**
     * Fetch records that have <code>active BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.News> fetchRangeOfActive(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(News.NEWS.ACTIVE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>active IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.News> fetchByActive(Boolean... values) {
        return fetch(News.NEWS.ACTIVE, values);
    }
}
