/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.daos;


import ch.schlierelacht.admin.jooq.AbstractSpringDAOImpl;
import ch.schlierelacht.admin.jooq.tables.OkMember;
import ch.schlierelacht.admin.jooq.tables.records.OkMemberRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class OkMemberDao extends AbstractSpringDAOImpl<OkMemberRecord, ch.schlierelacht.admin.jooq.tables.pojos.OkMember, Long> {

    /**
     * Create a new OkMemberDao without any configuration
     */
    public OkMemberDao() {
        super(OkMember.OK_MEMBER, ch.schlierelacht.admin.jooq.tables.pojos.OkMember.class);
    }

    /**
     * Create a new OkMemberDao with an attached configuration
     */
    @Autowired
    public OkMemberDao(Configuration configuration) {
        super(OkMember.OK_MEMBER, ch.schlierelacht.admin.jooq.tables.pojos.OkMember.class, configuration);
    }

    @Override
    public Long getId(ch.schlierelacht.admin.jooq.tables.pojos.OkMember object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.OkMember> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(OkMember.OK_MEMBER.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.OkMember> fetchById(Long... values) {
        return fetch(OkMember.OK_MEMBER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ch.schlierelacht.admin.jooq.tables.pojos.OkMember fetchOneById(Long value) {
        return fetchOne(OkMember.OK_MEMBER.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<ch.schlierelacht.admin.jooq.tables.pojos.OkMember> fetchOptionalById(Long value) {
        return fetchOptional(OkMember.OK_MEMBER.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.OkMember> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(OkMember.OK_MEMBER.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.OkMember> fetchByName(String... values) {
        return fetch(OkMember.OK_MEMBER.NAME, values);
    }

    /**
     * Fetch records that have <code>role BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.OkMember> fetchRangeOfRole(String lowerInclusive, String upperInclusive) {
        return fetchRange(OkMember.OK_MEMBER.ROLE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>role IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.OkMember> fetchByRole(String... values) {
        return fetch(OkMember.OK_MEMBER.ROLE, values);
    }

    /**
     * Fetch records that have <code>email BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.OkMember> fetchRangeOfEmail(String lowerInclusive, String upperInclusive) {
        return fetchRange(OkMember.OK_MEMBER.EMAIL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.OkMember> fetchByEmail(String... values) {
        return fetch(OkMember.OK_MEMBER.EMAIL, values);
    }

    /**
     * Fetch records that have <code>cloudflare_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.OkMember> fetchRangeOfCloudflareId(String lowerInclusive, String upperInclusive) {
        return fetchRange(OkMember.OK_MEMBER.CLOUDFLARE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>cloudflare_id IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.OkMember> fetchByCloudflareId(String... values) {
        return fetch(OkMember.OK_MEMBER.CLOUDFLARE_ID, values);
    }

    /**
     * Fetch records that have <code>sort_order BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.OkMember> fetchRangeOfSortOrder(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(OkMember.OK_MEMBER.SORT_ORDER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>sort_order IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.OkMember> fetchBySortOrder(Integer... values) {
        return fetch(OkMember.OK_MEMBER.SORT_ORDER, values);
    }
}
