/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.daos;


import ch.schlierelacht.admin.jooq.AbstractSpringDAOImpl;
import ch.schlierelacht.admin.jooq.enums.OkTeam;
import ch.schlierelacht.admin.jooq.tables.OkTeamMember;
import ch.schlierelacht.admin.jooq.tables.records.OkTeamMemberRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class OkTeamMemberDao extends AbstractSpringDAOImpl<OkTeamMemberRecord, ch.schlierelacht.admin.jooq.tables.pojos.OkTeamMember, Long> {

    /**
     * Create a new OkTeamMemberDao without any configuration
     */
    public OkTeamMemberDao() {
        super(OkTeamMember.OK_TEAM_MEMBER, ch.schlierelacht.admin.jooq.tables.pojos.OkTeamMember.class);
    }

    /**
     * Create a new OkTeamMemberDao with an attached configuration
     */
    @Autowired
    public OkTeamMemberDao(Configuration configuration) {
        super(OkTeamMember.OK_TEAM_MEMBER, ch.schlierelacht.admin.jooq.tables.pojos.OkTeamMember.class, configuration);
    }

    @Override
    public Long getId(ch.schlierelacht.admin.jooq.tables.pojos.OkTeamMember object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.OkTeamMember> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(OkTeamMember.OK_TEAM_MEMBER.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.OkTeamMember> fetchById(Long... values) {
        return fetch(OkTeamMember.OK_TEAM_MEMBER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ch.schlierelacht.admin.jooq.tables.pojos.OkTeamMember fetchOneById(Long value) {
        return fetchOne(OkTeamMember.OK_TEAM_MEMBER.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<ch.schlierelacht.admin.jooq.tables.pojos.OkTeamMember> fetchOptionalById(Long value) {
        return fetchOptional(OkTeamMember.OK_TEAM_MEMBER.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.OkTeamMember> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(OkTeamMember.OK_TEAM_MEMBER.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.OkTeamMember> fetchByName(String... values) {
        return fetch(OkTeamMember.OK_TEAM_MEMBER.NAME, values);
    }

    /**
     * Fetch records that have <code>team BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.OkTeamMember> fetchRangeOfTeam(OkTeam lowerInclusive, OkTeam upperInclusive) {
        return fetchRange(OkTeamMember.OK_TEAM_MEMBER.TEAM, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>team IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.OkTeamMember> fetchByTeam(OkTeam... values) {
        return fetch(OkTeamMember.OK_TEAM_MEMBER.TEAM, values);
    }

    /**
     * Fetch records that have <code>email BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.OkTeamMember> fetchRangeOfEmail(String lowerInclusive, String upperInclusive) {
        return fetchRange(OkTeamMember.OK_TEAM_MEMBER.EMAIL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.OkTeamMember> fetchByEmail(String... values) {
        return fetch(OkTeamMember.OK_TEAM_MEMBER.EMAIL, values);
    }
}
