/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.daos;


import ch.schlierelacht.admin.jooq.AbstractSpringDAOImpl;
import ch.schlierelacht.admin.jooq.tables.Programm;
import ch.schlierelacht.admin.jooq.tables.records.ProgrammRecord;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class ProgrammDao extends AbstractSpringDAOImpl<ProgrammRecord, ch.schlierelacht.admin.jooq.tables.pojos.Programm, Long> {

    /**
     * Create a new ProgrammDao without any configuration
     */
    public ProgrammDao() {
        super(Programm.PROGRAMM, ch.schlierelacht.admin.jooq.tables.pojos.Programm.class);
    }

    /**
     * Create a new ProgrammDao with an attached configuration
     */
    @Autowired
    public ProgrammDao(Configuration configuration) {
        super(Programm.PROGRAMM, ch.schlierelacht.admin.jooq.tables.pojos.Programm.class, configuration);
    }

    @Override
    public Long getId(ch.schlierelacht.admin.jooq.tables.pojos.Programm object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Programm> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Programm.PROGRAMM.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Programm> fetchById(Long... values) {
        return fetch(Programm.PROGRAMM.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ch.schlierelacht.admin.jooq.tables.pojos.Programm fetchOneById(Long value) {
        return fetchOne(Programm.PROGRAMM.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<ch.schlierelacht.admin.jooq.tables.pojos.Programm> fetchOptionalById(Long value) {
        return fetchOptional(Programm.PROGRAMM.ID, value);
    }

    /**
     * Fetch records that have <code>attraction_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Programm> fetchRangeOfAttractionId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Programm.PROGRAMM.ATTRACTION_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>attraction_id IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Programm> fetchByAttractionId(Long... values) {
        return fetch(Programm.PROGRAMM.ATTRACTION_ID, values);
    }

    /**
     * Fetch records that have <code>location_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Programm> fetchRangeOfLocationId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Programm.PROGRAMM.LOCATION_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>location_id IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Programm> fetchByLocationId(Long... values) {
        return fetch(Programm.PROGRAMM.LOCATION_ID, values);
    }

    /**
     * Fetch records that have <code>from_date BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Programm> fetchRangeOfFromDate(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(Programm.PROGRAMM.FROM_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>from_date IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Programm> fetchByFromDate(LocalDate... values) {
        return fetch(Programm.PROGRAMM.FROM_DATE, values);
    }

    /**
     * Fetch records that have <code>from_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Programm> fetchRangeOfFromTime(LocalTime lowerInclusive, LocalTime upperInclusive) {
        return fetchRange(Programm.PROGRAMM.FROM_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>from_time IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Programm> fetchByFromTime(LocalTime... values) {
        return fetch(Programm.PROGRAMM.FROM_TIME, values);
    }

    /**
     * Fetch records that have <code>to_date BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Programm> fetchRangeOfToDate(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(Programm.PROGRAMM.TO_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>to_date IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Programm> fetchByToDate(LocalDate... values) {
        return fetch(Programm.PROGRAMM.TO_DATE, values);
    }

    /**
     * Fetch records that have <code>to_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Programm> fetchRangeOfToTime(LocalTime lowerInclusive, LocalTime upperInclusive) {
        return fetchRange(Programm.PROGRAMM.TO_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>to_time IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Programm> fetchByToTime(LocalTime... values) {
        return fetch(Programm.PROGRAMM.TO_TIME, values);
    }
}
