/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.daos;


import ch.schlierelacht.admin.jooq.AbstractSpringDAOImpl;
import ch.schlierelacht.admin.jooq.tables.PushDeviceToken;
import ch.schlierelacht.admin.jooq.tables.records.PushDeviceTokenRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class PushDeviceTokenDao extends AbstractSpringDAOImpl<PushDeviceTokenRecord, ch.schlierelacht.admin.jooq.tables.pojos.PushDeviceToken, Long> {

    /**
     * Create a new PushDeviceTokenDao without any configuration
     */
    public PushDeviceTokenDao() {
        super(PushDeviceToken.PUSH_DEVICE_TOKEN, ch.schlierelacht.admin.jooq.tables.pojos.PushDeviceToken.class);
    }

    /**
     * Create a new PushDeviceTokenDao with an attached configuration
     */
    @Autowired
    public PushDeviceTokenDao(Configuration configuration) {
        super(PushDeviceToken.PUSH_DEVICE_TOKEN, ch.schlierelacht.admin.jooq.tables.pojos.PushDeviceToken.class, configuration);
    }

    @Override
    public Long getId(ch.schlierelacht.admin.jooq.tables.pojos.PushDeviceToken object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.PushDeviceToken> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(PushDeviceToken.PUSH_DEVICE_TOKEN.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.PushDeviceToken> fetchById(Long... values) {
        return fetch(PushDeviceToken.PUSH_DEVICE_TOKEN.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ch.schlierelacht.admin.jooq.tables.pojos.PushDeviceToken fetchOneById(Long value) {
        return fetchOne(PushDeviceToken.PUSH_DEVICE_TOKEN.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<ch.schlierelacht.admin.jooq.tables.pojos.PushDeviceToken> fetchOptionalById(Long value) {
        return fetchOptional(PushDeviceToken.PUSH_DEVICE_TOKEN.ID, value);
    }

    /**
     * Fetch records that have <code>token BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.PushDeviceToken> fetchRangeOfToken(String lowerInclusive, String upperInclusive) {
        return fetchRange(PushDeviceToken.PUSH_DEVICE_TOKEN.TOKEN, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>token IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.PushDeviceToken> fetchByToken(String... values) {
        return fetch(PushDeviceToken.PUSH_DEVICE_TOKEN.TOKEN, values);
    }

    /**
     * Fetch a unique record that has <code>token = value</code>
     */
    public ch.schlierelacht.admin.jooq.tables.pojos.PushDeviceToken fetchOneByToken(String value) {
        return fetchOne(PushDeviceToken.PUSH_DEVICE_TOKEN.TOKEN, value);
    }

    /**
     * Fetch a unique record that has <code>token = value</code>
     */
    public Optional<ch.schlierelacht.admin.jooq.tables.pojos.PushDeviceToken> fetchOptionalByToken(String value) {
        return fetchOptional(PushDeviceToken.PUSH_DEVICE_TOKEN.TOKEN, value);
    }

    /**
     * Fetch records that have <code>platform BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.PushDeviceToken> fetchRangeOfPlatform(String lowerInclusive, String upperInclusive) {
        return fetchRange(PushDeviceToken.PUSH_DEVICE_TOKEN.PLATFORM, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>platform IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.PushDeviceToken> fetchByPlatform(String... values) {
        return fetch(PushDeviceToken.PUSH_DEVICE_TOKEN.PLATFORM, values);
    }

    /**
     * Fetch records that have <code>locale BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.PushDeviceToken> fetchRangeOfLocale(String lowerInclusive, String upperInclusive) {
        return fetchRange(PushDeviceToken.PUSH_DEVICE_TOKEN.LOCALE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>locale IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.PushDeviceToken> fetchByLocale(String... values) {
        return fetch(PushDeviceToken.PUSH_DEVICE_TOKEN.LOCALE, values);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.PushDeviceToken> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(PushDeviceToken.PUSH_DEVICE_TOKEN.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.PushDeviceToken> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(PushDeviceToken.PUSH_DEVICE_TOKEN.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.PushDeviceToken> fetchRangeOfUpdatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(PushDeviceToken.PUSH_DEVICE_TOKEN.UPDATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.PushDeviceToken> fetchByUpdatedAt(LocalDateTime... values) {
        return fetch(PushDeviceToken.PUSH_DEVICE_TOKEN.UPDATED_AT, values);
    }
}
