/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.daos;


import ch.schlierelacht.admin.jooq.AbstractSpringDAOImpl;
import ch.schlierelacht.admin.jooq.enums.SponsoringType;
import ch.schlierelacht.admin.jooq.tables.Sponsoring;
import ch.schlierelacht.admin.jooq.tables.records.SponsoringRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class SponsoringDao extends AbstractSpringDAOImpl<SponsoringRecord, ch.schlierelacht.admin.jooq.tables.pojos.Sponsoring, Long> {

    /**
     * Create a new SponsoringDao without any configuration
     */
    public SponsoringDao() {
        super(Sponsoring.SPONSORING, ch.schlierelacht.admin.jooq.tables.pojos.Sponsoring.class);
    }

    /**
     * Create a new SponsoringDao with an attached configuration
     */
    @Autowired
    public SponsoringDao(Configuration configuration) {
        super(Sponsoring.SPONSORING, ch.schlierelacht.admin.jooq.tables.pojos.Sponsoring.class, configuration);
    }

    @Override
    public Long getId(ch.schlierelacht.admin.jooq.tables.pojos.Sponsoring object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Sponsoring> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Sponsoring.SPONSORING.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Sponsoring> fetchById(Long... values) {
        return fetch(Sponsoring.SPONSORING.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ch.schlierelacht.admin.jooq.tables.pojos.Sponsoring fetchOneById(Long value) {
        return fetchOne(Sponsoring.SPONSORING.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<ch.schlierelacht.admin.jooq.tables.pojos.Sponsoring> fetchOptionalById(Long value) {
        return fetchOptional(Sponsoring.SPONSORING.ID, value);
    }

    /**
     * Fetch records that have <code>type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Sponsoring> fetchRangeOfType(SponsoringType lowerInclusive, SponsoringType upperInclusive) {
        return fetchRange(Sponsoring.SPONSORING.TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Sponsoring> fetchByType(SponsoringType... values) {
        return fetch(Sponsoring.SPONSORING.TYPE, values);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Sponsoring> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Sponsoring.SPONSORING.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Sponsoring> fetchByName(String... values) {
        return fetch(Sponsoring.SPONSORING.NAME, values);
    }

    /**
     * Fetch records that have <code>cloudflare_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Sponsoring> fetchRangeOfCloudflareId(String lowerInclusive, String upperInclusive) {
        return fetchRange(Sponsoring.SPONSORING.CLOUDFLARE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>cloudflare_id IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Sponsoring> fetchByCloudflareId(String... values) {
        return fetch(Sponsoring.SPONSORING.CLOUDFLARE_ID, values);
    }

    /**
     * Fetch records that have <code>url BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Sponsoring> fetchRangeOfUrl(String lowerInclusive, String upperInclusive) {
        return fetchRange(Sponsoring.SPONSORING.URL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>url IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Sponsoring> fetchByUrl(String... values) {
        return fetch(Sponsoring.SPONSORING.URL, values);
    }
}
