/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.daos;


import ch.schlierelacht.admin.jooq.AbstractSpringDAOImpl;
import ch.schlierelacht.admin.jooq.enums.AttractionType;
import ch.schlierelacht.admin.jooq.tables.Tag;
import ch.schlierelacht.admin.jooq.tables.records.TagRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class TagDao extends AbstractSpringDAOImpl<TagRecord, ch.schlierelacht.admin.jooq.tables.pojos.Tag, Long> {

    /**
     * Create a new TagDao without any configuration
     */
    public TagDao() {
        super(Tag.TAG, ch.schlierelacht.admin.jooq.tables.pojos.Tag.class);
    }

    /**
     * Create a new TagDao with an attached configuration
     */
    @Autowired
    public TagDao(Configuration configuration) {
        super(Tag.TAG, ch.schlierelacht.admin.jooq.tables.pojos.Tag.class, configuration);
    }

    @Override
    public Long getId(ch.schlierelacht.admin.jooq.tables.pojos.Tag object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Tag> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Tag.TAG.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Tag> fetchById(Long... values) {
        return fetch(Tag.TAG.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ch.schlierelacht.admin.jooq.tables.pojos.Tag fetchOneById(Long value) {
        return fetchOne(Tag.TAG.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<ch.schlierelacht.admin.jooq.tables.pojos.Tag> fetchOptionalById(Long value) {
        return fetchOptional(Tag.TAG.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Tag> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Tag.TAG.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Tag> fetchByName(String... values) {
        return fetch(Tag.TAG.NAME, values);
    }

    /**
     * Fetch records that have <code>type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Tag> fetchRangeOfType(AttractionType lowerInclusive, AttractionType upperInclusive) {
        return fetchRange(Tag.TAG.TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<ch.schlierelacht.admin.jooq.tables.pojos.Tag> fetchByType(AttractionType... values) {
        return fetch(Tag.TAG.TYPE, values);
    }
}
