/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables;


import ch.schlierelacht.admin.jooq.Keys;
import ch.schlierelacht.admin.jooq.Public;
import ch.schlierelacht.admin.jooq.enums.AttractionType;
import ch.schlierelacht.admin.jooq.tables.AttractionImage.AttractionImagePath;
import ch.schlierelacht.admin.jooq.tables.AttractionTag.AttractionTagPath;
import ch.schlierelacht.admin.jooq.tables.Programm.ProgrammPath;
import ch.schlierelacht.admin.jooq.tables.Tag.TagPath;
import ch.schlierelacht.admin.jooq.tables.records.AttractionRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Attraction extends TableImpl<AttractionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.attraction</code>
     */
    public static final Attraction ATTRACTION = new Attraction();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AttractionRecord> getRecordType() {
        return AttractionRecord.class;
    }

    /**
     * The column <code>public.attraction.id</code>.
     */
    public final TableField<AttractionRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.attraction.type</code>.
     */
    public final TableField<AttractionRecord, AttractionType> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(AttractionType.class), this, "");

    /**
     * The column <code>public.attraction.name</code>.
     */
    public final TableField<AttractionRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.attraction.description</code>.
     */
    public final TableField<AttractionRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.attraction.website</code>.
     */
    public final TableField<AttractionRecord, String> WEBSITE = createField(DSL.name("website"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.attraction.instagram</code>.
     */
    public final TableField<AttractionRecord, String> INSTAGRAM = createField(DSL.name("instagram"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.attraction.facebook</code>.
     */
    public final TableField<AttractionRecord, String> FACEBOOK = createField(DSL.name("facebook"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.attraction.youtube</code>.
     */
    public final TableField<AttractionRecord, String> YOUTUBE = createField(DSL.name("youtube"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.attraction.external_id</code>.
     */
    public final TableField<AttractionRecord, String> EXTERNAL_ID = createField(DSL.name("external_id"), SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.field(DSL.raw("''::character varying"), SQLDataType.VARCHAR)), this, "");

    private Attraction(Name alias, Table<AttractionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Attraction(Name alias, Table<AttractionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.attraction</code> table reference
     */
    public Attraction(String alias) {
        this(DSL.name(alias), ATTRACTION);
    }

    /**
     * Create an aliased <code>public.attraction</code> table reference
     */
    public Attraction(Name alias) {
        this(alias, ATTRACTION);
    }

    /**
     * Create a <code>public.attraction</code> table reference
     */
    public Attraction() {
        this(DSL.name("attraction"), null);
    }

    public <O extends Record> Attraction(Table<O> path, ForeignKey<O, AttractionRecord> childPath, InverseForeignKey<O, AttractionRecord> parentPath) {
        super(path, childPath, parentPath, ATTRACTION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AttractionPath extends Attraction implements Path<AttractionRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AttractionPath(Table<O> path, ForeignKey<O, AttractionRecord> childPath, InverseForeignKey<O, AttractionRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AttractionPath(Name alias, Table<AttractionRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AttractionPath as(String alias) {
            return new AttractionPath(DSL.name(alias), this);
        }

        @Override
        public AttractionPath as(Name alias) {
            return new AttractionPath(alias, this);
        }

        @Override
        public AttractionPath as(Table<?> alias) {
            return new AttractionPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<AttractionRecord, Long> getIdentity() {
        return (Identity<AttractionRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AttractionRecord> getPrimaryKey() {
        return Keys.PK_ARTIST;
    }

    @Override
    public List<UniqueKey<AttractionRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UQ_ATTRACTION);
    }

    private transient AttractionImagePath _attractionImage;

    /**
     * Get the implicit to-many join path to the
     * <code>public.attraction_image</code> table
     */
    public AttractionImagePath attractionImage() {
        if (_attractionImage == null)
            _attractionImage = new AttractionImagePath(this, null, Keys.ATTRACTION_IMAGE__FK_ATTRACTION_IMAGE_ATTRACTION.getInverseKey());

        return _attractionImage;
    }

    private transient AttractionTagPath _attractionTag;

    /**
     * Get the implicit to-many join path to the
     * <code>public.attraction_tag</code> table
     */
    public AttractionTagPath attractionTag() {
        if (_attractionTag == null)
            _attractionTag = new AttractionTagPath(this, null, Keys.ATTRACTION_TAG__FK_ATTRACTION_TAG_ATTRACTION.getInverseKey());

        return _attractionTag;
    }

    private transient ProgrammPath _programm;

    /**
     * Get the implicit to-many join path to the <code>public.programm</code>
     * table
     */
    public ProgrammPath programm() {
        if (_programm == null)
            _programm = new ProgrammPath(this, null, Keys.PROGRAMM__FK_PROGRAMM_ATTRACTION.getInverseKey());

        return _programm;
    }

    /**
     * Get the implicit many-to-many join path to the <code>public.tag</code>
     * table
     */
    public TagPath tag() {
        return attractionTag().tag();
    }

    @Override
    public Attraction as(String alias) {
        return new Attraction(DSL.name(alias), this);
    }

    @Override
    public Attraction as(Name alias) {
        return new Attraction(alias, this);
    }

    @Override
    public Attraction as(Table<?> alias) {
        return new Attraction(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Attraction rename(String name) {
        return new Attraction(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Attraction rename(Name name) {
        return new Attraction(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Attraction rename(Table<?> name) {
        return new Attraction(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Attraction where(Condition condition) {
        return new Attraction(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Attraction where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Attraction where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Attraction where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Attraction where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Attraction where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Attraction where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Attraction where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Attraction whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Attraction whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
