/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables;


import ch.schlierelacht.admin.jooq.Keys;
import ch.schlierelacht.admin.jooq.Public;
import ch.schlierelacht.admin.jooq.enums.ImageType;
import ch.schlierelacht.admin.jooq.tables.Attraction.AttractionPath;
import ch.schlierelacht.admin.jooq.tables.Image.ImagePath;
import ch.schlierelacht.admin.jooq.tables.records.AttractionImageRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AttractionImage extends TableImpl<AttractionImageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.attraction_image</code>
     */
    public static final AttractionImage ATTRACTION_IMAGE = new AttractionImage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AttractionImageRecord> getRecordType() {
        return AttractionImageRecord.class;
    }

    /**
     * The column <code>public.attraction_image.attraction_id</code>.
     */
    public final TableField<AttractionImageRecord, Long> ATTRACTION_ID = createField(DSL.name("attraction_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.attraction_image.image_id</code>.
     */
    public final TableField<AttractionImageRecord, Long> IMAGE_ID = createField(DSL.name("image_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.attraction_image.type</code>.
     */
    public final TableField<AttractionImageRecord, ImageType> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(ImageType.class), this, "");

    private AttractionImage(Name alias, Table<AttractionImageRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AttractionImage(Name alias, Table<AttractionImageRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.attraction_image</code> table reference
     */
    public AttractionImage(String alias) {
        this(DSL.name(alias), ATTRACTION_IMAGE);
    }

    /**
     * Create an aliased <code>public.attraction_image</code> table reference
     */
    public AttractionImage(Name alias) {
        this(alias, ATTRACTION_IMAGE);
    }

    /**
     * Create a <code>public.attraction_image</code> table reference
     */
    public AttractionImage() {
        this(DSL.name("attraction_image"), null);
    }

    public <O extends Record> AttractionImage(Table<O> path, ForeignKey<O, AttractionImageRecord> childPath, InverseForeignKey<O, AttractionImageRecord> parentPath) {
        super(path, childPath, parentPath, ATTRACTION_IMAGE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AttractionImagePath extends AttractionImage implements Path<AttractionImageRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AttractionImagePath(Table<O> path, ForeignKey<O, AttractionImageRecord> childPath, InverseForeignKey<O, AttractionImageRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AttractionImagePath(Name alias, Table<AttractionImageRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AttractionImagePath as(String alias) {
            return new AttractionImagePath(DSL.name(alias), this);
        }

        @Override
        public AttractionImagePath as(Name alias) {
            return new AttractionImagePath(alias, this);
        }

        @Override
        public AttractionImagePath as(Table<?> alias) {
            return new AttractionImagePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<ForeignKey<AttractionImageRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ATTRACTION_IMAGE__FK_ATTRACTION_IMAGE_ATTRACTION, Keys.ATTRACTION_IMAGE__FK_ATTRACTION_IMAGE_IMAGE);
    }

    private transient AttractionPath _attraction;

    /**
     * Get the implicit join path to the <code>public.attraction</code> table.
     */
    public AttractionPath attraction() {
        if (_attraction == null)
            _attraction = new AttractionPath(this, Keys.ATTRACTION_IMAGE__FK_ATTRACTION_IMAGE_ATTRACTION, null);

        return _attraction;
    }

    private transient ImagePath _image;

    /**
     * Get the implicit join path to the <code>public.image</code> table.
     */
    public ImagePath image() {
        if (_image == null)
            _image = new ImagePath(this, Keys.ATTRACTION_IMAGE__FK_ATTRACTION_IMAGE_IMAGE, null);

        return _image;
    }

    @Override
    public AttractionImage as(String alias) {
        return new AttractionImage(DSL.name(alias), this);
    }

    @Override
    public AttractionImage as(Name alias) {
        return new AttractionImage(alias, this);
    }

    @Override
    public AttractionImage as(Table<?> alias) {
        return new AttractionImage(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AttractionImage rename(String name) {
        return new AttractionImage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AttractionImage rename(Name name) {
        return new AttractionImage(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AttractionImage rename(Table<?> name) {
        return new AttractionImage(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AttractionImage where(Condition condition) {
        return new AttractionImage(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AttractionImage where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AttractionImage where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AttractionImage where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AttractionImage where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AttractionImage where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AttractionImage where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AttractionImage where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AttractionImage whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AttractionImage whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
