/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables;


import ch.schlierelacht.admin.jooq.Keys;
import ch.schlierelacht.admin.jooq.Public;
import ch.schlierelacht.admin.jooq.tables.Attraction.AttractionPath;
import ch.schlierelacht.admin.jooq.tables.records.AttractionFileRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AttractionFile extends TableImpl<AttractionFileRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.attraction_file</code>
     */
    public static final AttractionFile ATTRACTION_FILE = new AttractionFile();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AttractionFileRecord> getRecordType() {
        return AttractionFileRecord.class;
    }

    /**
     * The column <code>public.attraction_file.id</code>.
     */
    public final TableField<AttractionFileRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.attraction_file.attraction_id</code>.
     */
    public final TableField<AttractionFileRecord, Long> ATTRACTION_ID = createField(DSL.name("attraction_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.attraction_file.filename</code>.
     */
    public final TableField<AttractionFileRecord, String> FILENAME = createField(DSL.name("filename"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.attraction_file.filetype</code>.
     */
    public final TableField<AttractionFileRecord, String> FILETYPE = createField(DSL.name("filetype"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.attraction_file.description</code>.
     */
    public final TableField<AttractionFileRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.attraction_file.filesize</code>.
     */
    public final TableField<AttractionFileRecord, Long> FILESIZE = createField(DSL.name("filesize"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.attraction_file.file_data</code>.
     */
    public final TableField<AttractionFileRecord, byte[]> FILE_DATA = createField(DSL.name("file_data"), SQLDataType.BLOB.nullable(false), this, "");

    /**
     * The column <code>public.attraction_file.uploaded_at</code>.
     */
    public final TableField<AttractionFileRecord, LocalDateTime> UPLOADED_AT = createField(DSL.name("uploaded_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.attraction_file.uploaded_by</code>.
     */
    public final TableField<AttractionFileRecord, String> UPLOADED_BY = createField(DSL.name("uploaded_by"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private AttractionFile(Name alias, Table<AttractionFileRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AttractionFile(Name alias, Table<AttractionFileRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.attraction_file</code> table reference
     */
    public AttractionFile(String alias) {
        this(DSL.name(alias), ATTRACTION_FILE);
    }

    /**
     * Create an aliased <code>public.attraction_file</code> table reference
     */
    public AttractionFile(Name alias) {
        this(alias, ATTRACTION_FILE);
    }

    /**
     * Create a <code>public.attraction_file</code> table reference
     */
    public AttractionFile() {
        this(DSL.name("attraction_file"), null);
    }

    public <O extends Record> AttractionFile(Table<O> path, ForeignKey<O, AttractionFileRecord> childPath, InverseForeignKey<O, AttractionFileRecord> parentPath) {
        super(path, childPath, parentPath, ATTRACTION_FILE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AttractionFilePath extends AttractionFile implements Path<AttractionFileRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AttractionFilePath(Table<O> path, ForeignKey<O, AttractionFileRecord> childPath, InverseForeignKey<O, AttractionFileRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AttractionFilePath(Name alias, Table<AttractionFileRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AttractionFilePath as(String alias) {
            return new AttractionFilePath(DSL.name(alias), this);
        }

        @Override
        public AttractionFilePath as(Name alias) {
            return new AttractionFilePath(alias, this);
        }

        @Override
        public AttractionFilePath as(Table<?> alias) {
            return new AttractionFilePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AttractionFileRecord> getPrimaryKey() {
        return Keys.PK_ATTRACTION_FILE;
    }

    @Override
    public List<ForeignKey<AttractionFileRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ATTRACTION_FILE__FK_ATTRACTION_FILE_ATTRACTION);
    }

    private transient AttractionPath _attraction;

    /**
     * Get the implicit join path to the <code>public.attraction</code> table.
     */
    public AttractionPath attraction() {
        if (_attraction == null)
            _attraction = new AttractionPath(this, Keys.ATTRACTION_FILE__FK_ATTRACTION_FILE_ATTRACTION, null);

        return _attraction;
    }

    @Override
    public AttractionFile as(String alias) {
        return new AttractionFile(DSL.name(alias), this);
    }

    @Override
    public AttractionFile as(Name alias) {
        return new AttractionFile(alias, this);
    }

    @Override
    public AttractionFile as(Table<?> alias) {
        return new AttractionFile(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AttractionFile rename(String name) {
        return new AttractionFile(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AttractionFile rename(Name name) {
        return new AttractionFile(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AttractionFile rename(Table<?> name) {
        return new AttractionFile(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AttractionFile where(Condition condition) {
        return new AttractionFile(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AttractionFile where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AttractionFile where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AttractionFile where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AttractionFile where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AttractionFile where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AttractionFile where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AttractionFile where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AttractionFile whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AttractionFile whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
