/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables;


import ch.schlierelacht.admin.jooq.Keys;
import ch.schlierelacht.admin.jooq.Public;
import ch.schlierelacht.admin.jooq.tables.Attraction.AttractionPath;
import ch.schlierelacht.admin.jooq.tables.Tag.TagPath;
import ch.schlierelacht.admin.jooq.tables.records.AttractionTagRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AttractionTag extends TableImpl<AttractionTagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.attraction_tag</code>
     */
    public static final AttractionTag ATTRACTION_TAG = new AttractionTag();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AttractionTagRecord> getRecordType() {
        return AttractionTagRecord.class;
    }

    /**
     * The column <code>public.attraction_tag.attraction_id</code>.
     */
    public final TableField<AttractionTagRecord, Long> ATTRACTION_ID = createField(DSL.name("attraction_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.attraction_tag.tag_id</code>.
     */
    public final TableField<AttractionTagRecord, Long> TAG_ID = createField(DSL.name("tag_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private AttractionTag(Name alias, Table<AttractionTagRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AttractionTag(Name alias, Table<AttractionTagRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.attraction_tag</code> table reference
     */
    public AttractionTag(String alias) {
        this(DSL.name(alias), ATTRACTION_TAG);
    }

    /**
     * Create an aliased <code>public.attraction_tag</code> table reference
     */
    public AttractionTag(Name alias) {
        this(alias, ATTRACTION_TAG);
    }

    /**
     * Create a <code>public.attraction_tag</code> table reference
     */
    public AttractionTag() {
        this(DSL.name("attraction_tag"), null);
    }

    public <O extends Record> AttractionTag(Table<O> path, ForeignKey<O, AttractionTagRecord> childPath, InverseForeignKey<O, AttractionTagRecord> parentPath) {
        super(path, childPath, parentPath, ATTRACTION_TAG);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AttractionTagPath extends AttractionTag implements Path<AttractionTagRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AttractionTagPath(Table<O> path, ForeignKey<O, AttractionTagRecord> childPath, InverseForeignKey<O, AttractionTagRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AttractionTagPath(Name alias, Table<AttractionTagRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AttractionTagPath as(String alias) {
            return new AttractionTagPath(DSL.name(alias), this);
        }

        @Override
        public AttractionTagPath as(Name alias) {
            return new AttractionTagPath(alias, this);
        }

        @Override
        public AttractionTagPath as(Table<?> alias) {
            return new AttractionTagPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AttractionTagRecord> getPrimaryKey() {
        return Keys.PK_ATTRACTION_TAG;
    }

    @Override
    public List<ForeignKey<AttractionTagRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ATTRACTION_TAG__FK_ATTRACTION_TAG_ATTRACTION, Keys.ATTRACTION_TAG__FK_ATTRACTION_TAG_TAG);
    }

    private transient AttractionPath _attraction;

    /**
     * Get the implicit join path to the <code>public.attraction</code> table.
     */
    public AttractionPath attraction() {
        if (_attraction == null)
            _attraction = new AttractionPath(this, Keys.ATTRACTION_TAG__FK_ATTRACTION_TAG_ATTRACTION, null);

        return _attraction;
    }

    private transient TagPath _tag;

    /**
     * Get the implicit join path to the <code>public.tag</code> table.
     */
    public TagPath tag() {
        if (_tag == null)
            _tag = new TagPath(this, Keys.ATTRACTION_TAG__FK_ATTRACTION_TAG_TAG, null);

        return _tag;
    }

    @Override
    public AttractionTag as(String alias) {
        return new AttractionTag(DSL.name(alias), this);
    }

    @Override
    public AttractionTag as(Name alias) {
        return new AttractionTag(alias, this);
    }

    @Override
    public AttractionTag as(Table<?> alias) {
        return new AttractionTag(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AttractionTag rename(String name) {
        return new AttractionTag(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AttractionTag rename(Name name) {
        return new AttractionTag(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AttractionTag rename(Table<?> name) {
        return new AttractionTag(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AttractionTag where(Condition condition) {
        return new AttractionTag(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AttractionTag where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AttractionTag where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AttractionTag where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AttractionTag where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AttractionTag where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AttractionTag where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AttractionTag where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AttractionTag whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AttractionTag whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
