/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables;


import ch.schlierelacht.admin.jooq.Keys;
import ch.schlierelacht.admin.jooq.Public;
import ch.schlierelacht.admin.jooq.enums.DownloadCategory;
import ch.schlierelacht.admin.jooq.tables.records.DownloadRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Download extends TableImpl<DownloadRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.download</code>
     */
    public static final Download DOWNLOAD = new Download();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DownloadRecord> getRecordType() {
        return DownloadRecord.class;
    }

    /**
     * The column <code>public.download.id</code>.
     */
    public final TableField<DownloadRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.download.uploaded_at</code>.
     */
    public final TableField<DownloadRecord, LocalDateTime> UPLOADED_AT = createField(DSL.name("uploaded_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.download.uploaded_by</code>.
     */
    public final TableField<DownloadRecord, String> UPLOADED_BY = createField(DSL.name("uploaded_by"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.download.filename</code>.
     */
    public final TableField<DownloadRecord, String> FILENAME = createField(DSL.name("filename"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.download.filetype</code>.
     */
    public final TableField<DownloadRecord, String> FILETYPE = createField(DSL.name("filetype"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.download.description</code>.
     */
    public final TableField<DownloadRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.download.filesize</code>.
     */
    public final TableField<DownloadRecord, Long> FILESIZE = createField(DSL.name("filesize"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.download.category</code>.
     */
    public final TableField<DownloadRecord, DownloadCategory> CATEGORY = createField(DSL.name("category"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(DownloadCategory.class), this, "");

    /**
     * The column <code>public.download.file_data</code>.
     */
    public final TableField<DownloadRecord, byte[]> FILE_DATA = createField(DSL.name("file_data"), SQLDataType.BLOB.nullable(false), this, "");

    private Download(Name alias, Table<DownloadRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Download(Name alias, Table<DownloadRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.download</code> table reference
     */
    public Download(String alias) {
        this(DSL.name(alias), DOWNLOAD);
    }

    /**
     * Create an aliased <code>public.download</code> table reference
     */
    public Download(Name alias) {
        this(alias, DOWNLOAD);
    }

    /**
     * Create a <code>public.download</code> table reference
     */
    public Download() {
        this(DSL.name("download"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<DownloadRecord, Long> getIdentity() {
        return (Identity<DownloadRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<DownloadRecord> getPrimaryKey() {
        return Keys.PK_DOWNLOAD;
    }

    @Override
    public Download as(String alias) {
        return new Download(DSL.name(alias), this);
    }

    @Override
    public Download as(Name alias) {
        return new Download(alias, this);
    }

    @Override
    public Download as(Table<?> alias) {
        return new Download(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Download rename(String name) {
        return new Download(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Download rename(Name name) {
        return new Download(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Download rename(Table<?> name) {
        return new Download(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Download where(Condition condition) {
        return new Download(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Download where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Download where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Download where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Download where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Download where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Download where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Download where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Download whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Download whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
