/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables;


import ch.schlierelacht.admin.jooq.Keys;
import ch.schlierelacht.admin.jooq.Public;
import ch.schlierelacht.admin.jooq.tables.records.GalleryCategoryRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GalleryCategory extends TableImpl<GalleryCategoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.gallery_category</code>
     */
    public static final GalleryCategory GALLERY_CATEGORY = new GalleryCategory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GalleryCategoryRecord> getRecordType() {
        return GalleryCategoryRecord.class;
    }

    /**
     * The column <code>public.gallery_category.id</code>.
     */
    public final TableField<GalleryCategoryRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.gallery_category.name</code>.
     */
    public final TableField<GalleryCategoryRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.gallery_category.sort_order</code>.
     */
    public final TableField<GalleryCategoryRecord, Integer> SORT_ORDER = createField(DSL.name("sort_order"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    private GalleryCategory(Name alias, Table<GalleryCategoryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GalleryCategory(Name alias, Table<GalleryCategoryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.gallery_category</code> table reference
     */
    public GalleryCategory(String alias) {
        this(DSL.name(alias), GALLERY_CATEGORY);
    }

    /**
     * Create an aliased <code>public.gallery_category</code> table reference
     */
    public GalleryCategory(Name alias) {
        this(alias, GALLERY_CATEGORY);
    }

    /**
     * Create a <code>public.gallery_category</code> table reference
     */
    public GalleryCategory() {
        this(DSL.name("gallery_category"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<GalleryCategoryRecord> getPrimaryKey() {
        return Keys.PK_GALLERY_CATEGORY;
    }

    @Override
    public List<UniqueKey<GalleryCategoryRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UQ_GALLERY_CATEGORY_NAME);
    }

    @Override
    public GalleryCategory as(String alias) {
        return new GalleryCategory(DSL.name(alias), this);
    }

    @Override
    public GalleryCategory as(Name alias) {
        return new GalleryCategory(alias, this);
    }

    @Override
    public GalleryCategory as(Table<?> alias) {
        return new GalleryCategory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GalleryCategory rename(String name) {
        return new GalleryCategory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GalleryCategory rename(Name name) {
        return new GalleryCategory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GalleryCategory rename(Table<?> name) {
        return new GalleryCategory(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GalleryCategory where(Condition condition) {
        return new GalleryCategory(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GalleryCategory where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GalleryCategory where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GalleryCategory where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GalleryCategory where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GalleryCategory where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GalleryCategory where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GalleryCategory where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GalleryCategory whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GalleryCategory whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
