/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables;


import ch.schlierelacht.admin.jooq.Indexes;
import ch.schlierelacht.admin.jooq.Keys;
import ch.schlierelacht.admin.jooq.Public;
import ch.schlierelacht.admin.jooq.tables.records.GalleryImageRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GalleryImage extends TableImpl<GalleryImageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.gallery_image</code>
     */
    public static final GalleryImage GALLERY_IMAGE = new GalleryImage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GalleryImageRecord> getRecordType() {
        return GalleryImageRecord.class;
    }

    /**
     * The column <code>public.gallery_image.id</code>.
     */
    public final TableField<GalleryImageRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>public.gallery_image.category</code>.
     */
    public final TableField<GalleryImageRecord, String> CATEGORY = createField(DSL.name("category"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.gallery_image.cloudflare_id</code>.
     */
    public final TableField<GalleryImageRecord, String> CLOUDFLARE_ID = createField(DSL.name("cloudflare_id"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.gallery_image.uploaded_at</code>.
     */
    public final TableField<GalleryImageRecord, LocalDateTime> UPLOADED_AT = createField(DSL.name("uploaded_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.gallery_image.uploaded_by</code>.
     */
    public final TableField<GalleryImageRecord, String> UPLOADED_BY = createField(DSL.name("uploaded_by"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private GalleryImage(Name alias, Table<GalleryImageRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GalleryImage(Name alias, Table<GalleryImageRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.gallery_image</code> table reference
     */
    public GalleryImage(String alias) {
        this(DSL.name(alias), GALLERY_IMAGE);
    }

    /**
     * Create an aliased <code>public.gallery_image</code> table reference
     */
    public GalleryImage(Name alias) {
        this(alias, GALLERY_IMAGE);
    }

    /**
     * Create a <code>public.gallery_image</code> table reference
     */
    public GalleryImage() {
        this(DSL.name("gallery_image"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_GALLERY_IMAGE_CATEGORY);
    }

    @Override
    public Identity<GalleryImageRecord, Long> getIdentity() {
        return (Identity<GalleryImageRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<GalleryImageRecord> getPrimaryKey() {
        return Keys.PK_GALLERY_IMAGE;
    }

    @Override
    public GalleryImage as(String alias) {
        return new GalleryImage(DSL.name(alias), this);
    }

    @Override
    public GalleryImage as(Name alias) {
        return new GalleryImage(alias, this);
    }

    @Override
    public GalleryImage as(Table<?> alias) {
        return new GalleryImage(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GalleryImage rename(String name) {
        return new GalleryImage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GalleryImage rename(Name name) {
        return new GalleryImage(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GalleryImage rename(Table<?> name) {
        return new GalleryImage(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GalleryImage where(Condition condition) {
        return new GalleryImage(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GalleryImage where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GalleryImage where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GalleryImage where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GalleryImage where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GalleryImage where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GalleryImage where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GalleryImage where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GalleryImage whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GalleryImage whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
