/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables;


import ch.schlierelacht.admin.jooq.Keys;
import ch.schlierelacht.admin.jooq.Public;
import ch.schlierelacht.admin.jooq.tables.AttractionImage.AttractionImagePath;
import ch.schlierelacht.admin.jooq.tables.records.ImageRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Image extends TableImpl<ImageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.image</code>
     */
    public static final Image IMAGE = new Image();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ImageRecord> getRecordType() {
        return ImageRecord.class;
    }

    /**
     * The column <code>public.image.id</code>.
     */
    public final TableField<ImageRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.image.cloudflare_id</code>.
     */
    public final TableField<ImageRecord, String> CLOUDFLARE_ID = createField(DSL.name("cloudflare_id"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.image.description</code>.
     */
    public final TableField<ImageRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.image.width</code>.
     */
    public final TableField<ImageRecord, Integer> WIDTH = createField(DSL.name("width"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.image.height</code>.
     */
    public final TableField<ImageRecord, Integer> HEIGHT = createField(DSL.name("height"), SQLDataType.INTEGER.nullable(false), this, "");

    private Image(Name alias, Table<ImageRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Image(Name alias, Table<ImageRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.image</code> table reference
     */
    public Image(String alias) {
        this(DSL.name(alias), IMAGE);
    }

    /**
     * Create an aliased <code>public.image</code> table reference
     */
    public Image(Name alias) {
        this(alias, IMAGE);
    }

    /**
     * Create a <code>public.image</code> table reference
     */
    public Image() {
        this(DSL.name("image"), null);
    }

    public <O extends Record> Image(Table<O> path, ForeignKey<O, ImageRecord> childPath, InverseForeignKey<O, ImageRecord> parentPath) {
        super(path, childPath, parentPath, IMAGE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ImagePath extends Image implements Path<ImageRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ImagePath(Table<O> path, ForeignKey<O, ImageRecord> childPath, InverseForeignKey<O, ImageRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ImagePath(Name alias, Table<ImageRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ImagePath as(String alias) {
            return new ImagePath(DSL.name(alias), this);
        }

        @Override
        public ImagePath as(Name alias) {
            return new ImagePath(alias, this);
        }

        @Override
        public ImagePath as(Table<?> alias) {
            return new ImagePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ImageRecord, Long> getIdentity() {
        return (Identity<ImageRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ImageRecord> getPrimaryKey() {
        return Keys.PK_IMAGE;
    }

    @Override
    public List<UniqueKey<ImageRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UQ_IMAGE);
    }

    private transient AttractionImagePath _attractionImage;

    /**
     * Get the implicit to-many join path to the
     * <code>public.attraction_image</code> table
     */
    public AttractionImagePath attractionImage() {
        if (_attractionImage == null)
            _attractionImage = new AttractionImagePath(this, null, Keys.ATTRACTION_IMAGE__FK_ATTRACTION_IMAGE_IMAGE.getInverseKey());

        return _attractionImage;
    }

    @Override
    public Image as(String alias) {
        return new Image(DSL.name(alias), this);
    }

    @Override
    public Image as(Name alias) {
        return new Image(alias, this);
    }

    @Override
    public Image as(Table<?> alias) {
        return new Image(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Image rename(String name) {
        return new Image(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Image rename(Name name) {
        return new Image(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Image rename(Table<?> name) {
        return new Image(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Image where(Condition condition) {
        return new Image(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Image where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Image where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Image where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Image where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Image where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Image where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Image where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Image whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Image whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
