/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables;


import ch.schlierelacht.admin.jooq.Keys;
import ch.schlierelacht.admin.jooq.Public;
import ch.schlierelacht.admin.jooq.enums.MeetupJahrgang;
import ch.schlierelacht.admin.jooq.tables.records.MeetupRegistrationRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MeetupRegistration extends TableImpl<MeetupRegistrationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.meetup_registration</code>
     */
    public static final MeetupRegistration MEETUP_REGISTRATION = new MeetupRegistration();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MeetupRegistrationRecord> getRecordType() {
        return MeetupRegistrationRecord.class;
    }

    /**
     * The column <code>public.meetup_registration.id</code>.
     */
    public final TableField<MeetupRegistrationRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.meetup_registration.registered_at</code>.
     */
    public final TableField<MeetupRegistrationRecord, LocalDateTime> REGISTERED_AT = createField(DSL.name("registered_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.meetup_registration.firstname</code>.
     */
    public final TableField<MeetupRegistrationRecord, String> FIRSTNAME = createField(DSL.name("firstname"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.meetup_registration.lastname</code>.
     */
    public final TableField<MeetupRegistrationRecord, String> LASTNAME = createField(DSL.name("lastname"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.meetup_registration.email</code>.
     */
    public final TableField<MeetupRegistrationRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.meetup_registration.jahrgang</code>.
     */
    public final TableField<MeetupRegistrationRecord, MeetupJahrgang> JAHRGANG = createField(DSL.name("jahrgang"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(MeetupJahrgang.class), this, "");

    /**
     * The column <code>public.meetup_registration.show_on_list</code>.
     */
    public final TableField<MeetupRegistrationRecord, Boolean> SHOW_ON_LIST = createField(DSL.name("show_on_list"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    private MeetupRegistration(Name alias, Table<MeetupRegistrationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MeetupRegistration(Name alias, Table<MeetupRegistrationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.meetup_registration</code> table reference
     */
    public MeetupRegistration(String alias) {
        this(DSL.name(alias), MEETUP_REGISTRATION);
    }

    /**
     * Create an aliased <code>public.meetup_registration</code> table reference
     */
    public MeetupRegistration(Name alias) {
        this(alias, MEETUP_REGISTRATION);
    }

    /**
     * Create a <code>public.meetup_registration</code> table reference
     */
    public MeetupRegistration() {
        this(DSL.name("meetup_registration"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<MeetupRegistrationRecord> getPrimaryKey() {
        return Keys.PK_MEETUP_REGISTRATION;
    }

    @Override
    public MeetupRegistration as(String alias) {
        return new MeetupRegistration(DSL.name(alias), this);
    }

    @Override
    public MeetupRegistration as(Name alias) {
        return new MeetupRegistration(alias, this);
    }

    @Override
    public MeetupRegistration as(Table<?> alias) {
        return new MeetupRegistration(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MeetupRegistration rename(String name) {
        return new MeetupRegistration(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MeetupRegistration rename(Name name) {
        return new MeetupRegistration(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MeetupRegistration rename(Table<?> name) {
        return new MeetupRegistration(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MeetupRegistration where(Condition condition) {
        return new MeetupRegistration(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MeetupRegistration where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MeetupRegistration where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MeetupRegistration where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MeetupRegistration where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MeetupRegistration where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MeetupRegistration where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MeetupRegistration where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MeetupRegistration whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MeetupRegistration whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
