/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables;


import ch.schlierelacht.admin.jooq.Keys;
import ch.schlierelacht.admin.jooq.Public;
import ch.schlierelacht.admin.jooq.tables.records.OkMemberRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OkMember extends TableImpl<OkMemberRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.ok_member</code>
     */
    public static final OkMember OK_MEMBER = new OkMember();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OkMemberRecord> getRecordType() {
        return OkMemberRecord.class;
    }

    /**
     * The column <code>public.ok_member.id</code>.
     */
    public final TableField<OkMemberRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.ok_member.name</code>.
     */
    public final TableField<OkMemberRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.ok_member.role</code>.
     */
    public final TableField<OkMemberRecord, String> ROLE = createField(DSL.name("role"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.ok_member.email</code>.
     */
    public final TableField<OkMemberRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.ok_member.cloudflare_id</code>.
     */
    public final TableField<OkMemberRecord, String> CLOUDFLARE_ID = createField(DSL.name("cloudflare_id"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.ok_member.sort_order</code>.
     */
    public final TableField<OkMemberRecord, Integer> SORT_ORDER = createField(DSL.name("sort_order"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    private OkMember(Name alias, Table<OkMemberRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private OkMember(Name alias, Table<OkMemberRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.ok_member</code> table reference
     */
    public OkMember(String alias) {
        this(DSL.name(alias), OK_MEMBER);
    }

    /**
     * Create an aliased <code>public.ok_member</code> table reference
     */
    public OkMember(Name alias) {
        this(alias, OK_MEMBER);
    }

    /**
     * Create a <code>public.ok_member</code> table reference
     */
    public OkMember() {
        this(DSL.name("ok_member"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<OkMemberRecord> getPrimaryKey() {
        return Keys.PK_OK_MEMBER;
    }

    @Override
    public OkMember as(String alias) {
        return new OkMember(DSL.name(alias), this);
    }

    @Override
    public OkMember as(Name alias) {
        return new OkMember(alias, this);
    }

    @Override
    public OkMember as(Table<?> alias) {
        return new OkMember(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OkMember rename(String name) {
        return new OkMember(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OkMember rename(Name name) {
        return new OkMember(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OkMember rename(Table<?> name) {
        return new OkMember(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OkMember where(Condition condition) {
        return new OkMember(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OkMember where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OkMember where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OkMember where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OkMember where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OkMember where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OkMember where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OkMember where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OkMember whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OkMember whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
