/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables;


import ch.schlierelacht.admin.jooq.Keys;
import ch.schlierelacht.admin.jooq.Public;
import ch.schlierelacht.admin.jooq.enums.OkTeam;
import ch.schlierelacht.admin.jooq.tables.records.OkTeamMemberRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OkTeamMember extends TableImpl<OkTeamMemberRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.ok_team_member</code>
     */
    public static final OkTeamMember OK_TEAM_MEMBER = new OkTeamMember();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OkTeamMemberRecord> getRecordType() {
        return OkTeamMemberRecord.class;
    }

    /**
     * The column <code>public.ok_team_member.id</code>.
     */
    public final TableField<OkTeamMemberRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.ok_team_member.name</code>.
     */
    public final TableField<OkTeamMemberRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.ok_team_member.team</code>.
     */
    public final TableField<OkTeamMemberRecord, OkTeam> TEAM = createField(DSL.name("team"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(OkTeam.class), this, "");

    private OkTeamMember(Name alias, Table<OkTeamMemberRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private OkTeamMember(Name alias, Table<OkTeamMemberRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.ok_team_member</code> table reference
     */
    public OkTeamMember(String alias) {
        this(DSL.name(alias), OK_TEAM_MEMBER);
    }

    /**
     * Create an aliased <code>public.ok_team_member</code> table reference
     */
    public OkTeamMember(Name alias) {
        this(alias, OK_TEAM_MEMBER);
    }

    /**
     * Create a <code>public.ok_team_member</code> table reference
     */
    public OkTeamMember() {
        this(DSL.name("ok_team_member"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<OkTeamMemberRecord> getPrimaryKey() {
        return Keys.PK_OK_TEAM_MEMBER;
    }

    @Override
    public OkTeamMember as(String alias) {
        return new OkTeamMember(DSL.name(alias), this);
    }

    @Override
    public OkTeamMember as(Name alias) {
        return new OkTeamMember(alias, this);
    }

    @Override
    public OkTeamMember as(Table<?> alias) {
        return new OkTeamMember(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OkTeamMember rename(String name) {
        return new OkTeamMember(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OkTeamMember rename(Name name) {
        return new OkTeamMember(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OkTeamMember rename(Table<?> name) {
        return new OkTeamMember(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OkTeamMember where(Condition condition) {
        return new OkTeamMember(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OkTeamMember where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OkTeamMember where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OkTeamMember where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OkTeamMember where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OkTeamMember where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OkTeamMember where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OkTeamMember where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OkTeamMember whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OkTeamMember whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
