/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables;


import ch.schlierelacht.admin.jooq.Keys;
import ch.schlierelacht.admin.jooq.Public;
import ch.schlierelacht.admin.jooq.tables.Attraction.AttractionPath;
import ch.schlierelacht.admin.jooq.tables.Location.LocationPath;
import ch.schlierelacht.admin.jooq.tables.records.ProgrammRecord;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Programm extends TableImpl<ProgrammRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.programm</code>
     */
    public static final Programm PROGRAMM = new Programm();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProgrammRecord> getRecordType() {
        return ProgrammRecord.class;
    }

    /**
     * The column <code>public.programm.id</code>.
     */
    public final TableField<ProgrammRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.programm.attraction_id</code>.
     */
    public final TableField<ProgrammRecord, Long> ATTRACTION_ID = createField(DSL.name("attraction_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.programm.location_id</code>.
     */
    public final TableField<ProgrammRecord, Long> LOCATION_ID = createField(DSL.name("location_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.programm.from_date</code>.
     */
    public final TableField<ProgrammRecord, LocalDate> FROM_DATE = createField(DSL.name("from_date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>public.programm.from_time</code>.
     */
    public final TableField<ProgrammRecord, LocalTime> FROM_TIME = createField(DSL.name("from_time"), SQLDataType.LOCALTIME(6), this, "");

    /**
     * The column <code>public.programm.to_date</code>.
     */
    public final TableField<ProgrammRecord, LocalDate> TO_DATE = createField(DSL.name("to_date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.programm.to_time</code>.
     */
    public final TableField<ProgrammRecord, LocalTime> TO_TIME = createField(DSL.name("to_time"), SQLDataType.LOCALTIME(6), this, "");

    private Programm(Name alias, Table<ProgrammRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Programm(Name alias, Table<ProgrammRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.programm</code> table reference
     */
    public Programm(String alias) {
        this(DSL.name(alias), PROGRAMM);
    }

    /**
     * Create an aliased <code>public.programm</code> table reference
     */
    public Programm(Name alias) {
        this(alias, PROGRAMM);
    }

    /**
     * Create a <code>public.programm</code> table reference
     */
    public Programm() {
        this(DSL.name("programm"), null);
    }

    public <O extends Record> Programm(Table<O> path, ForeignKey<O, ProgrammRecord> childPath, InverseForeignKey<O, ProgrammRecord> parentPath) {
        super(path, childPath, parentPath, PROGRAMM);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ProgrammPath extends Programm implements Path<ProgrammRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ProgrammPath(Table<O> path, ForeignKey<O, ProgrammRecord> childPath, InverseForeignKey<O, ProgrammRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ProgrammPath(Name alias, Table<ProgrammRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ProgrammPath as(String alias) {
            return new ProgrammPath(DSL.name(alias), this);
        }

        @Override
        public ProgrammPath as(Name alias) {
            return new ProgrammPath(alias, this);
        }

        @Override
        public ProgrammPath as(Table<?> alias) {
            return new ProgrammPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ProgrammRecord, Long> getIdentity() {
        return (Identity<ProgrammRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProgrammRecord> getPrimaryKey() {
        return Keys.PK_PROGRAMM;
    }

    @Override
    public List<ForeignKey<ProgrammRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PROGRAMM__FK_PROGRAMM_ATTRACTION, Keys.PROGRAMM__FK_PROGRAMM_LOCATION);
    }

    private transient AttractionPath _attraction;

    /**
     * Get the implicit join path to the <code>public.attraction</code> table.
     */
    public AttractionPath attraction() {
        if (_attraction == null)
            _attraction = new AttractionPath(this, Keys.PROGRAMM__FK_PROGRAMM_ATTRACTION, null);

        return _attraction;
    }

    private transient LocationPath _location;

    /**
     * Get the implicit join path to the <code>public.location</code> table.
     */
    public LocationPath location() {
        if (_location == null)
            _location = new LocationPath(this, Keys.PROGRAMM__FK_PROGRAMM_LOCATION, null);

        return _location;
    }

    @Override
    public Programm as(String alias) {
        return new Programm(DSL.name(alias), this);
    }

    @Override
    public Programm as(Name alias) {
        return new Programm(alias, this);
    }

    @Override
    public Programm as(Table<?> alias) {
        return new Programm(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Programm rename(String name) {
        return new Programm(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Programm rename(Name name) {
        return new Programm(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Programm rename(Table<?> name) {
        return new Programm(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Programm where(Condition condition) {
        return new Programm(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Programm where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Programm where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Programm where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Programm where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Programm where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Programm where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Programm where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Programm whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Programm whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
