/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables;


import ch.schlierelacht.admin.jooq.Keys;
import ch.schlierelacht.admin.jooq.Public;
import ch.schlierelacht.admin.jooq.tables.records.PushDeviceTokenRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PushDeviceToken extends TableImpl<PushDeviceTokenRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.push_device_token</code>
     */
    public static final PushDeviceToken PUSH_DEVICE_TOKEN = new PushDeviceToken();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PushDeviceTokenRecord> getRecordType() {
        return PushDeviceTokenRecord.class;
    }

    /**
     * The column <code>public.push_device_token.id</code>.
     */
    public final TableField<PushDeviceTokenRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>public.push_device_token.token</code>.
     */
    public final TableField<PushDeviceTokenRecord, String> TOKEN = createField(DSL.name("token"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.push_device_token.platform</code>.
     */
    public final TableField<PushDeviceTokenRecord, String> PLATFORM = createField(DSL.name("platform"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>public.push_device_token.locale</code>.
     */
    public final TableField<PushDeviceTokenRecord, String> LOCALE = createField(DSL.name("locale"), SQLDataType.VARCHAR(8), this, "");

    /**
     * The column <code>public.push_device_token.created_at</code>.
     */
    public final TableField<PushDeviceTokenRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.push_device_token.updated_at</code>.
     */
    public final TableField<PushDeviceTokenRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private PushDeviceToken(Name alias, Table<PushDeviceTokenRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PushDeviceToken(Name alias, Table<PushDeviceTokenRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.push_device_token</code> table reference
     */
    public PushDeviceToken(String alias) {
        this(DSL.name(alias), PUSH_DEVICE_TOKEN);
    }

    /**
     * Create an aliased <code>public.push_device_token</code> table reference
     */
    public PushDeviceToken(Name alias) {
        this(alias, PUSH_DEVICE_TOKEN);
    }

    /**
     * Create a <code>public.push_device_token</code> table reference
     */
    public PushDeviceToken() {
        this(DSL.name("push_device_token"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<PushDeviceTokenRecord, Long> getIdentity() {
        return (Identity<PushDeviceTokenRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PushDeviceTokenRecord> getPrimaryKey() {
        return Keys.PK_PUSH_DEVICE_TOKEN;
    }

    @Override
    public List<UniqueKey<PushDeviceTokenRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UQ_PUSH_DEVICE_TOKEN_TOKEN);
    }

    @Override
    public PushDeviceToken as(String alias) {
        return new PushDeviceToken(DSL.name(alias), this);
    }

    @Override
    public PushDeviceToken as(Name alias) {
        return new PushDeviceToken(alias, this);
    }

    @Override
    public PushDeviceToken as(Table<?> alias) {
        return new PushDeviceToken(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PushDeviceToken rename(String name) {
        return new PushDeviceToken(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PushDeviceToken rename(Name name) {
        return new PushDeviceToken(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PushDeviceToken rename(Table<?> name) {
        return new PushDeviceToken(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PushDeviceToken where(Condition condition) {
        return new PushDeviceToken(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PushDeviceToken where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PushDeviceToken where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PushDeviceToken where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PushDeviceToken where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PushDeviceToken where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PushDeviceToken where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PushDeviceToken where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PushDeviceToken whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PushDeviceToken whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
