/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables;


import ch.schlierelacht.admin.jooq.Keys;
import ch.schlierelacht.admin.jooq.Public;
import ch.schlierelacht.admin.jooq.enums.SponsoringType;
import ch.schlierelacht.admin.jooq.tables.records.SponsoringRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sponsoring extends TableImpl<SponsoringRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.sponsoring</code>
     */
    public static final Sponsoring SPONSORING = new Sponsoring();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SponsoringRecord> getRecordType() {
        return SponsoringRecord.class;
    }

    /**
     * The column <code>public.sponsoring.id</code>.
     */
    public final TableField<SponsoringRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.sponsoring.type</code>.
     */
    public final TableField<SponsoringRecord, SponsoringType> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(SponsoringType.class), this, "");

    /**
     * The column <code>public.sponsoring.name</code>.
     */
    public final TableField<SponsoringRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.sponsoring.cloudflare_id</code>.
     */
    public final TableField<SponsoringRecord, String> CLOUDFLARE_ID = createField(DSL.name("cloudflare_id"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.sponsoring.url</code>.
     */
    public final TableField<SponsoringRecord, String> URL = createField(DSL.name("url"), SQLDataType.VARCHAR(255), this, "");

    private Sponsoring(Name alias, Table<SponsoringRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Sponsoring(Name alias, Table<SponsoringRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.sponsoring</code> table reference
     */
    public Sponsoring(String alias) {
        this(DSL.name(alias), SPONSORING);
    }

    /**
     * Create an aliased <code>public.sponsoring</code> table reference
     */
    public Sponsoring(Name alias) {
        this(alias, SPONSORING);
    }

    /**
     * Create a <code>public.sponsoring</code> table reference
     */
    public Sponsoring() {
        this(DSL.name("sponsoring"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<SponsoringRecord, Long> getIdentity() {
        return (Identity<SponsoringRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SponsoringRecord> getPrimaryKey() {
        return Keys.PK_SPONSORING;
    }

    @Override
    public Sponsoring as(String alias) {
        return new Sponsoring(DSL.name(alias), this);
    }

    @Override
    public Sponsoring as(Name alias) {
        return new Sponsoring(alias, this);
    }

    @Override
    public Sponsoring as(Table<?> alias) {
        return new Sponsoring(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Sponsoring rename(String name) {
        return new Sponsoring(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Sponsoring rename(Name name) {
        return new Sponsoring(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Sponsoring rename(Table<?> name) {
        return new Sponsoring(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sponsoring where(Condition condition) {
        return new Sponsoring(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sponsoring where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sponsoring where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sponsoring where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sponsoring where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sponsoring where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sponsoring where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sponsoring where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sponsoring whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sponsoring whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
