/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.enums;


import ch.schlierelacht.admin.jooq.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum AttractionType implements EnumType {

    ARTIST("ARTIST"),

    FOOD("FOOD"),

    EXHIBITION("EXHIBITION"),

    DISCUSSION("DISCUSSION"),

    EVENT("EVENT"),

    RIDE("RIDE");

    private final String literal;

    private AttractionType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "attraction_type";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static AttractionType lookupLiteral(String literal) {
        return EnumType.lookupLiteral(AttractionType.class, literal);
    }
}
