/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.enums;


import ch.schlierelacht.admin.jooq.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum MeetupJahrgang implements EnumType {

    BEFORE_1954("BEFORE_1954"),

    BORN_1954_1958("BORN_1954_1958"),

    BORN_1959_1963("BORN_1959_1963"),

    BORN_1965_1968("BORN_1965_1968"),

    BORN_1969_1973("BORN_1969_1973"),

    BORN_1974_1978("BORN_1974_1978"),

    BORN_1979_1983("BORN_1979_1983"),

    BORN_1984_1988("BORN_1984_1988"),

    BORN_1989_1993("BORN_1989_1993"),

    BORN_1994_1998("BORN_1994_1998"),

    AFTER_1998("AFTER_1998");

    private final String literal;

    private MeetupJahrgang(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "meetup_jahrgang";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static MeetupJahrgang lookupLiteral(String literal) {
        return EnumType.lookupLiteral(MeetupJahrgang.class, literal);
    }
}
