/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.enums;


import ch.schlierelacht.admin.jooq.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum OkTeam implements EnumType {

    PRAESIDIALES_STADT_KOMMUNIKATION_FINANZEN("PRAESIDIALES_STADT_KOMMUNIKATION_FINANZEN"),

    BAU_INFRASTRUKTUR("BAU_INFRASTRUKTUR"),

    GASTRONOMIE("GASTRONOMIE"),

    PROGRAMM_AKTIVITAETEN("PROGRAMM_AKTIVITAETEN"),

    SICHERHEIT("SICHERHEIT"),

    SPONSORING("SPONSORING");

    private final String literal;

    private OkTeam(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "ok_team";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static OkTeam lookupLiteral(String literal) {
        return EnumType.lookupLiteral(OkTeam.class, literal);
    }
}
