/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq;


import ch.schlierelacht.admin.jooq.tables.AttractionImage;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index UQ_ATTRACTION_ONE_MAIN_IMAGE = Internal.createIndex(DSL.name("uq_attraction_one_main_image"), AttractionImage.ATTRACTION_IMAGE, new OrderField[] { AttractionImage.ATTRACTION_IMAGE.ATTRACTION_ID }, true);
}
