/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq;


import ch.schlierelacht.admin.jooq.tables.Attraction;
import ch.schlierelacht.admin.jooq.tables.AttractionImage;
import ch.schlierelacht.admin.jooq.tables.AttractionTag;
import ch.schlierelacht.admin.jooq.tables.Download;
import ch.schlierelacht.admin.jooq.tables.Image;
import ch.schlierelacht.admin.jooq.tables.Location;
import ch.schlierelacht.admin.jooq.tables.Login;
import ch.schlierelacht.admin.jooq.tables.MeetupRegistration;
import ch.schlierelacht.admin.jooq.tables.News;
import ch.schlierelacht.admin.jooq.tables.OkMember;
import ch.schlierelacht.admin.jooq.tables.OkTeamMember;
import ch.schlierelacht.admin.jooq.tables.Programm;
import ch.schlierelacht.admin.jooq.tables.Sponsoring;
import ch.schlierelacht.admin.jooq.tables.Tag;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * standard public schema
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.attraction</code>.
     */
    public final Attraction ATTRACTION = Attraction.ATTRACTION;

    /**
     * The table <code>public.attraction_image</code>.
     */
    public final AttractionImage ATTRACTION_IMAGE = AttractionImage.ATTRACTION_IMAGE;

    /**
     * The table <code>public.attraction_tag</code>.
     */
    public final AttractionTag ATTRACTION_TAG = AttractionTag.ATTRACTION_TAG;

    /**
     * The table <code>public.download</code>.
     */
    public final Download DOWNLOAD = Download.DOWNLOAD;

    /**
     * The table <code>public.image</code>.
     */
    public final Image IMAGE = Image.IMAGE;

    /**
     * The table <code>public.location</code>.
     */
    public final Location LOCATION = Location.LOCATION;

    /**
     * The table <code>public.login</code>.
     */
    public final Login LOGIN = Login.LOGIN;

    /**
     * The table <code>public.meetup_registration</code>.
     */
    public final MeetupRegistration MEETUP_REGISTRATION = MeetupRegistration.MEETUP_REGISTRATION;

    /**
     * The table <code>public.news</code>.
     */
    public final News NEWS = News.NEWS;

    /**
     * The table <code>public.ok_member</code>.
     */
    public final OkMember OK_MEMBER = OkMember.OK_MEMBER;

    /**
     * The table <code>public.ok_team_member</code>.
     */
    public final OkTeamMember OK_TEAM_MEMBER = OkTeamMember.OK_TEAM_MEMBER;

    /**
     * The table <code>public.programm</code>.
     */
    public final Programm PROGRAMM = Programm.PROGRAMM;

    /**
     * The table <code>public.sponsoring</code>.
     */
    public final Sponsoring SPONSORING = Sponsoring.SPONSORING;

    /**
     * The table <code>public.tag</code>.
     */
    public final Tag TAG = Tag.TAG;

    /**
     * No further instances allowed
     */
    private Public() {
        super(DSL.name("public"), null, DSL.comment("standard public schema"));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Attraction.ATTRACTION,
            AttractionImage.ATTRACTION_IMAGE,
            AttractionTag.ATTRACTION_TAG,
            Download.DOWNLOAD,
            Image.IMAGE,
            Location.LOCATION,
            Login.LOGIN,
            MeetupRegistration.MEETUP_REGISTRATION,
            News.NEWS,
            OkMember.OK_MEMBER,
            OkTeamMember.OK_TEAM_MEMBER,
            Programm.PROGRAMM,
            Sponsoring.SPONSORING,
            Tag.TAG
        );
    }
}
