/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq;


import ch.schlierelacht.admin.jooq.tables.Attraction;
import ch.schlierelacht.admin.jooq.tables.AttractionImage;
import ch.schlierelacht.admin.jooq.tables.Image;
import ch.schlierelacht.admin.jooq.tables.Location;
import ch.schlierelacht.admin.jooq.tables.Login;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.attraction</code>.
     */
    public final Attraction ATTRACTION = Attraction.ATTRACTION;

    /**
     * The table <code>public.attraction_image</code>.
     */
    public final AttractionImage ATTRACTION_IMAGE = AttractionImage.ATTRACTION_IMAGE;

    /**
     * The table <code>public.image</code>.
     */
    public final Image IMAGE = Image.IMAGE;

    /**
     * The table <code>public.location</code>.
     */
    public final Location LOCATION = Location.LOCATION;

    /**
     * The table <code>public.login</code>.
     */
    public final Login LOGIN = Login.LOGIN;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Attraction.ATTRACTION,
            AttractionImage.ATTRACTION_IMAGE,
            Image.IMAGE,
            Location.LOCATION,
            Login.LOGIN
        );
    }
}
