/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq;


import ch.schlierelacht.admin.jooq.tables.Login;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.login</code>.
     */
    public static final Login LOGIN = Login.LOGIN;
}
