/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq;


import ch.schlierelacht.admin.jooq.tables.Attraction;
import ch.schlierelacht.admin.jooq.tables.AttractionImage;
import ch.schlierelacht.admin.jooq.tables.Image;
import ch.schlierelacht.admin.jooq.tables.Location;
import ch.schlierelacht.admin.jooq.tables.Login;
import ch.schlierelacht.admin.jooq.tables.Programm;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.attraction</code>.
     */
    public static final Attraction ATTRACTION = Attraction.ATTRACTION;

    /**
     * The table <code>public.attraction_image</code>.
     */
    public static final AttractionImage ATTRACTION_IMAGE = AttractionImage.ATTRACTION_IMAGE;

    /**
     * The table <code>public.image</code>.
     */
    public static final Image IMAGE = Image.IMAGE;

    /**
     * The table <code>public.location</code>.
     */
    public static final Location LOCATION = Location.LOCATION;

    /**
     * The table <code>public.login</code>.
     */
    public static final Login LOGIN = Login.LOGIN;

    /**
     * The table <code>public.programm</code>.
     */
    public static final Programm PROGRAMM = Programm.PROGRAMM;
}
