/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.records;


import ch.schlierelacht.admin.jooq.tables.AttractionTag;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AttractionTagRecord extends UpdatableRecordImpl<AttractionTagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.attraction_tag.attraction_id</code>.
     */
    public void setAttractionId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.attraction_tag.attraction_id</code>.
     */
    public Long getAttractionId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.attraction_tag.tag_id</code>.
     */
    public void setTagId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.attraction_tag.tag_id</code>.
     */
    public Long getTagId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AttractionTagRecord
     */
    public AttractionTagRecord() {
        super(AttractionTag.ATTRACTION_TAG);
    }

    /**
     * Create a detached, initialised AttractionTagRecord
     */
    public AttractionTagRecord(Long attractionId, Long tagId) {
        super(AttractionTag.ATTRACTION_TAG);

        setAttractionId(attractionId);
        setTagId(tagId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AttractionTagRecord
     */
    public AttractionTagRecord(ch.schlierelacht.admin.jooq.tables.pojos.AttractionTag value) {
        super(AttractionTag.ATTRACTION_TAG);

        if (value != null) {
            setAttractionId(value.getAttractionId());
            setTagId(value.getTagId());
            resetChangedOnNotNull();
        }
    }
}
