/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.records;


import ch.schlierelacht.admin.jooq.enums.AttractionType;
import ch.schlierelacht.admin.jooq.tables.Attraction;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AttractionRecord extends UpdatableRecordImpl<AttractionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.attraction.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.attraction.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.attraction.type</code>.
     */
    public void setType(AttractionType value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.attraction.type</code>.
     */
    public AttractionType getType() {
        return (AttractionType) get(1);
    }

    /**
     * Setter for <code>public.attraction.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.attraction.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.attraction.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.attraction.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.attraction.website</code>.
     */
    public void setWebsite(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.attraction.website</code>.
     */
    public String getWebsite() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.attraction.instagram</code>.
     */
    public void setInstagram(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.attraction.instagram</code>.
     */
    public String getInstagram() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.attraction.facebook</code>.
     */
    public void setFacebook(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.attraction.facebook</code>.
     */
    public String getFacebook() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.attraction.youtube</code>.
     */
    public void setYoutube(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.attraction.youtube</code>.
     */
    public String getYoutube() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.attraction.external_id</code>.
     */
    public void setExternalId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.attraction.external_id</code>.
     */
    public String getExternalId() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AttractionRecord
     */
    public AttractionRecord() {
        super(Attraction.ATTRACTION);
    }

    /**
     * Create a detached, initialised AttractionRecord
     */
    public AttractionRecord(Long id, AttractionType type, String name, String description, String website, String instagram, String facebook, String youtube, String externalId) {
        super(Attraction.ATTRACTION);

        setId(id);
        setType(type);
        setName(name);
        setDescription(description);
        setWebsite(website);
        setInstagram(instagram);
        setFacebook(facebook);
        setYoutube(youtube);
        setExternalId(externalId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AttractionRecord
     */
    public AttractionRecord(ch.schlierelacht.admin.jooq.tables.pojos.Attraction value) {
        super(Attraction.ATTRACTION);

        if (value != null) {
            setId(value.getId());
            setType(value.getType());
            setName(value.getName());
            setDescription(value.getDescription());
            setWebsite(value.getWebsite());
            setInstagram(value.getInstagram());
            setFacebook(value.getFacebook());
            setYoutube(value.getYoutube());
            setExternalId(value.getExternalId());
            resetChangedOnNotNull();
        }
    }
}
