/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.records;


import ch.schlierelacht.admin.jooq.enums.ImageType;
import ch.schlierelacht.admin.jooq.tables.AttractionImage;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AttractionImageRecord extends TableRecordImpl<AttractionImageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.attraction_image.attraction_id</code>.
     */
    public void setAttractionId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.attraction_image.attraction_id</code>.
     */
    public Long getAttractionId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.attraction_image.image_id</code>.
     */
    public void setImageId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.attraction_image.image_id</code>.
     */
    public Long getImageId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.attraction_image.type</code>.
     */
    public void setType(ImageType value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.attraction_image.type</code>.
     */
    public ImageType getType() {
        return (ImageType) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AttractionImageRecord
     */
    public AttractionImageRecord() {
        super(AttractionImage.ATTRACTION_IMAGE);
    }

    /**
     * Create a detached, initialised AttractionImageRecord
     */
    public AttractionImageRecord(Long attractionId, Long imageId, ImageType type) {
        super(AttractionImage.ATTRACTION_IMAGE);

        setAttractionId(attractionId);
        setImageId(imageId);
        setType(type);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AttractionImageRecord
     */
    public AttractionImageRecord(ch.schlierelacht.admin.jooq.tables.pojos.AttractionImage value) {
        super(AttractionImage.ATTRACTION_IMAGE);

        if (value != null) {
            setAttractionId(value.getAttractionId());
            setImageId(value.getImageId());
            setType(value.getType());
            resetChangedOnNotNull();
        }
    }
}
