/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.records;


import ch.schlierelacht.admin.jooq.tables.AttractionFile;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AttractionFileRecord extends UpdatableRecordImpl<AttractionFileRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.attraction_file.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.attraction_file.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.attraction_file.attraction_id</code>.
     */
    public void setAttractionId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.attraction_file.attraction_id</code>.
     */
    public Long getAttractionId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.attraction_file.filename</code>.
     */
    public void setFilename(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.attraction_file.filename</code>.
     */
    public String getFilename() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.attraction_file.filetype</code>.
     */
    public void setFiletype(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.attraction_file.filetype</code>.
     */
    public String getFiletype() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.attraction_file.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.attraction_file.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.attraction_file.filesize</code>.
     */
    public void setFilesize(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.attraction_file.filesize</code>.
     */
    public Long getFilesize() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.attraction_file.file_data</code>.
     */
    public void setFileData(byte[] value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.attraction_file.file_data</code>.
     */
    public byte[] getFileData() {
        return (byte[]) get(6);
    }

    /**
     * Setter for <code>public.attraction_file.uploaded_at</code>.
     */
    public void setUploadedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.attraction_file.uploaded_at</code>.
     */
    public LocalDateTime getUploadedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.attraction_file.uploaded_by</code>.
     */
    public void setUploadedBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.attraction_file.uploaded_by</code>.
     */
    public String getUploadedBy() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AttractionFileRecord
     */
    public AttractionFileRecord() {
        super(AttractionFile.ATTRACTION_FILE);
    }

    /**
     * Create a detached, initialised AttractionFileRecord
     */
    public AttractionFileRecord(Long id, Long attractionId, String filename, String filetype, String description, Long filesize, byte[] fileData, LocalDateTime uploadedAt, String uploadedBy) {
        super(AttractionFile.ATTRACTION_FILE);

        setId(id);
        setAttractionId(attractionId);
        setFilename(filename);
        setFiletype(filetype);
        setDescription(description);
        setFilesize(filesize);
        setFileData(fileData);
        setUploadedAt(uploadedAt);
        setUploadedBy(uploadedBy);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised AttractionFileRecord
     */
    public AttractionFileRecord(ch.schlierelacht.admin.jooq.tables.pojos.AttractionFile value) {
        super(AttractionFile.ATTRACTION_FILE);

        if (value != null) {
            setId(value.getId());
            setAttractionId(value.getAttractionId());
            setFilename(value.getFilename());
            setFiletype(value.getFiletype());
            setDescription(value.getDescription());
            setFilesize(value.getFilesize());
            setFileData(value.getFileData());
            setUploadedAt(value.getUploadedAt());
            setUploadedBy(value.getUploadedBy());
            resetTouchedOnNotNull();
        }
    }
}
