/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.records;


import ch.schlierelacht.admin.jooq.enums.DownloadCategory;
import ch.schlierelacht.admin.jooq.tables.Download;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DownloadRecord extends UpdatableRecordImpl<DownloadRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.download.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.download.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.download.uploaded_at</code>.
     */
    public void setUploadedAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.download.uploaded_at</code>.
     */
    public LocalDateTime getUploadedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.download.uploaded_by</code>.
     */
    public void setUploadedBy(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.download.uploaded_by</code>.
     */
    public String getUploadedBy() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.download.filename</code>.
     */
    public void setFilename(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.download.filename</code>.
     */
    public String getFilename() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.download.filetype</code>.
     */
    public void setFiletype(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.download.filetype</code>.
     */
    public String getFiletype() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.download.description</code>.
     */
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.download.description</code>.
     */
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.download.filesize</code>.
     */
    public void setFilesize(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.download.filesize</code>.
     */
    public Long getFilesize() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.download.category</code>.
     */
    public void setCategory(DownloadCategory value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.download.category</code>.
     */
    public DownloadCategory getCategory() {
        return (DownloadCategory) get(7);
    }

    /**
     * Setter for <code>public.download.file_data</code>.
     */
    public void setFileData(byte[] value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.download.file_data</code>.
     */
    public byte[] getFileData() {
        return (byte[]) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DownloadRecord
     */
    public DownloadRecord() {
        super(Download.DOWNLOAD);
    }

    /**
     * Create a detached, initialised DownloadRecord
     */
    public DownloadRecord(Long id, LocalDateTime uploadedAt, String uploadedBy, String filename, String filetype, String description, Long filesize, DownloadCategory category, byte[] fileData) {
        super(Download.DOWNLOAD);

        setId(id);
        setUploadedAt(uploadedAt);
        setUploadedBy(uploadedBy);
        setFilename(filename);
        setFiletype(filetype);
        setDescription(description);
        setFilesize(filesize);
        setCategory(category);
        setFileData(fileData);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised DownloadRecord
     */
    public DownloadRecord(ch.schlierelacht.admin.jooq.tables.pojos.Download value) {
        super(Download.DOWNLOAD);

        if (value != null) {
            setId(value.getId());
            setUploadedAt(value.getUploadedAt());
            setUploadedBy(value.getUploadedBy());
            setFilename(value.getFilename());
            setFiletype(value.getFiletype());
            setDescription(value.getDescription());
            setFilesize(value.getFilesize());
            setCategory(value.getCategory());
            setFileData(value.getFileData());
            resetChangedOnNotNull();
        }
    }
}
