/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.records;


import ch.schlierelacht.admin.jooq.tables.GalleryImage;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GalleryImageRecord extends UpdatableRecordImpl<GalleryImageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.gallery_image.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.gallery_image.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.gallery_image.category</code>.
     */
    public void setCategory(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.gallery_image.category</code>.
     */
    public String getCategory() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.gallery_image.cloudflare_id</code>.
     */
    public void setCloudflareId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.gallery_image.cloudflare_id</code>.
     */
    public String getCloudflareId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.gallery_image.uploaded_at</code>.
     */
    public void setUploadedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.gallery_image.uploaded_at</code>.
     */
    public LocalDateTime getUploadedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.gallery_image.uploaded_by</code>.
     */
    public void setUploadedBy(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.gallery_image.uploaded_by</code>.
     */
    public String getUploadedBy() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GalleryImageRecord
     */
    public GalleryImageRecord() {
        super(GalleryImage.GALLERY_IMAGE);
    }

    /**
     * Create a detached, initialised GalleryImageRecord
     */
    public GalleryImageRecord(Long id, String category, String cloudflareId, LocalDateTime uploadedAt, String uploadedBy) {
        super(GalleryImage.GALLERY_IMAGE);

        setId(id);
        setCategory(category);
        setCloudflareId(cloudflareId);
        setUploadedAt(uploadedAt);
        setUploadedBy(uploadedBy);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised GalleryImageRecord
     */
    public GalleryImageRecord(ch.schlierelacht.admin.jooq.tables.pojos.GalleryImage value) {
        super(GalleryImage.GALLERY_IMAGE);

        if (value != null) {
            setId(value.getId());
            setCategory(value.getCategory());
            setCloudflareId(value.getCloudflareId());
            setUploadedAt(value.getUploadedAt());
            setUploadedBy(value.getUploadedBy());
            resetTouchedOnNotNull();
        }
    }
}
