/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.records;


import ch.schlierelacht.admin.jooq.tables.GalleryCategory;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GalleryCategoryRecord extends UpdatableRecordImpl<GalleryCategoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.gallery_category.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.gallery_category.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.gallery_category.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.gallery_category.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.gallery_category.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.gallery_category.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GalleryCategoryRecord
     */
    public GalleryCategoryRecord() {
        super(GalleryCategory.GALLERY_CATEGORY);
    }

    /**
     * Create a detached, initialised GalleryCategoryRecord
     */
    public GalleryCategoryRecord(Long id, String name, Integer sortOrder) {
        super(GalleryCategory.GALLERY_CATEGORY);

        setId(id);
        setName(name);
        setSortOrder(sortOrder);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised GalleryCategoryRecord
     */
    public GalleryCategoryRecord(ch.schlierelacht.admin.jooq.tables.pojos.GalleryCategory value) {
        super(GalleryCategory.GALLERY_CATEGORY);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setSortOrder(value.getSortOrder());
            resetTouchedOnNotNull();
        }
    }
}
