/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.records;


import ch.schlierelacht.admin.jooq.tables.Image;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ImageRecord extends UpdatableRecordImpl<ImageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.image.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.image.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.image.cloudflare_id</code>.
     */
    public void setCloudflareId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.image.cloudflare_id</code>.
     */
    public String getCloudflareId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.image.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.image.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.image.width</code>.
     */
    public void setWidth(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.image.width</code>.
     */
    public Integer getWidth() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.image.height</code>.
     */
    public void setHeight(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.image.height</code>.
     */
    public Integer getHeight() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ImageRecord
     */
    public ImageRecord() {
        super(Image.IMAGE);
    }

    /**
     * Create a detached, initialised ImageRecord
     */
    public ImageRecord(Long id, String cloudflareId, String description, Integer width, Integer height) {
        super(Image.IMAGE);

        setId(id);
        setCloudflareId(cloudflareId);
        setDescription(description);
        setWidth(width);
        setHeight(height);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ImageRecord
     */
    public ImageRecord(ch.schlierelacht.admin.jooq.tables.pojos.Image value) {
        super(Image.IMAGE);

        if (value != null) {
            setId(value.getId());
            setCloudflareId(value.getCloudflareId());
            setDescription(value.getDescription());
            setWidth(value.getWidth());
            setHeight(value.getHeight());
            resetChangedOnNotNull();
        }
    }
}
