/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.records;


import ch.schlierelacht.admin.jooq.enums.LocationType;
import ch.schlierelacht.admin.jooq.tables.Location;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LocationRecord extends UpdatableRecordImpl<LocationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.location.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.location.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.location.external_id</code>.
     */
    public void setExternalId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.location.external_id</code>.
     */
    public String getExternalId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.location.type</code>.
     */
    public void setType(LocationType value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.location.type</code>.
     */
    public LocationType getType() {
        return (LocationType) get(2);
    }

    /**
     * Setter for <code>public.location.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.location.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.location.latitude</code>.
     */
    public void setLatitude(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.location.latitude</code>.
     */
    public BigDecimal getLatitude() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>public.location.longitude</code>.
     */
    public void setLongitude(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.location.longitude</code>.
     */
    public BigDecimal getLongitude() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>public.location.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.location.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.location.cloudflare_id</code>.
     */
    public void setCloudflareId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.location.cloudflare_id</code>.
     */
    public String getCloudflareId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.location.map_id</code>.
     */
    public void setMapId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.location.map_id</code>.
     */
    public String getMapId() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LocationRecord
     */
    public LocationRecord() {
        super(Location.LOCATION);
    }

    /**
     * Create a detached, initialised LocationRecord
     */
    public LocationRecord(Long id, String externalId, LocationType type, String name, BigDecimal latitude, BigDecimal longitude, Integer sortOrder, String cloudflareId, String mapId) {
        super(Location.LOCATION);

        setId(id);
        setExternalId(externalId);
        setType(type);
        setName(name);
        setLatitude(latitude);
        setLongitude(longitude);
        setSortOrder(sortOrder);
        setCloudflareId(cloudflareId);
        setMapId(mapId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised LocationRecord
     */
    public LocationRecord(ch.schlierelacht.admin.jooq.tables.pojos.Location value) {
        super(Location.LOCATION);

        if (value != null) {
            setId(value.getId());
            setExternalId(value.getExternalId());
            setType(value.getType());
            setName(value.getName());
            setLatitude(value.getLatitude());
            setLongitude(value.getLongitude());
            setSortOrder(value.getSortOrder());
            setCloudflareId(value.getCloudflareId());
            setMapId(value.getMapId());
            resetChangedOnNotNull();
        }
    }
}
