/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.records;


import ch.schlierelacht.admin.jooq.enums.MeetupJahrgang;
import ch.schlierelacht.admin.jooq.tables.MeetupRegistration;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MeetupRegistrationRecord extends UpdatableRecordImpl<MeetupRegistrationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.meetup_registration.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.meetup_registration.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.meetup_registration.registered_at</code>.
     */
    public void setRegisteredAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.meetup_registration.registered_at</code>.
     */
    public LocalDateTime getRegisteredAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.meetup_registration.firstname</code>.
     */
    public void setFirstname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.meetup_registration.firstname</code>.
     */
    public String getFirstname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.meetup_registration.lastname</code>.
     */
    public void setLastname(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.meetup_registration.lastname</code>.
     */
    public String getLastname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.meetup_registration.email</code>.
     */
    public void setEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.meetup_registration.email</code>.
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.meetup_registration.jahrgang</code>.
     */
    public void setJahrgang(MeetupJahrgang value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.meetup_registration.jahrgang</code>.
     */
    public MeetupJahrgang getJahrgang() {
        return (MeetupJahrgang) get(5);
    }

    /**
     * Setter for <code>public.meetup_registration.show_on_list</code>.
     */
    public void setShowOnList(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.meetup_registration.show_on_list</code>.
     */
    public Boolean getShowOnList() {
        return (Boolean) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MeetupRegistrationRecord
     */
    public MeetupRegistrationRecord() {
        super(MeetupRegistration.MEETUP_REGISTRATION);
    }

    /**
     * Create a detached, initialised MeetupRegistrationRecord
     */
    public MeetupRegistrationRecord(Long id, LocalDateTime registeredAt, String firstname, String lastname, String email, MeetupJahrgang jahrgang, Boolean showOnList) {
        super(MeetupRegistration.MEETUP_REGISTRATION);

        setId(id);
        setRegisteredAt(registeredAt);
        setFirstname(firstname);
        setLastname(lastname);
        setEmail(email);
        setJahrgang(jahrgang);
        setShowOnList(showOnList);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised MeetupRegistrationRecord
     */
    public MeetupRegistrationRecord(ch.schlierelacht.admin.jooq.tables.pojos.MeetupRegistration value) {
        super(MeetupRegistration.MEETUP_REGISTRATION);

        if (value != null) {
            setId(value.getId());
            setRegisteredAt(value.getRegisteredAt());
            setFirstname(value.getFirstname());
            setLastname(value.getLastname());
            setEmail(value.getEmail());
            setJahrgang(value.getJahrgang());
            setShowOnList(value.getShowOnList());
            resetChangedOnNotNull();
        }
    }
}
