/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.records;


import ch.schlierelacht.admin.jooq.tables.News;

import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NewsRecord extends UpdatableRecordImpl<NewsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.news.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.news.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.news.date</code>.
     */
    public void setDate(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.news.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>public.news.title</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.news.title</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.news.intro_text</code>.
     */
    public void setIntroText(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.news.intro_text</code>.
     */
    public String getIntroText() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.news.full_text</code>.
     */
    public void setFullText(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.news.full_text</code>.
     */
    public String getFullText() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.news.cloudflare_id</code>.
     */
    public void setCloudflareId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.news.cloudflare_id</code>.
     */
    public String getCloudflareId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.news.active</code>.
     */
    public void setActive(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.news.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NewsRecord
     */
    public NewsRecord() {
        super(News.NEWS);
    }

    /**
     * Create a detached, initialised NewsRecord
     */
    public NewsRecord(Long id, LocalDate date, String title, String introText, String fullText, String cloudflareId, Boolean active) {
        super(News.NEWS);

        setId(id);
        setDate(date);
        setTitle(title);
        setIntroText(introText);
        setFullText(fullText);
        setCloudflareId(cloudflareId);
        setActive(active);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised NewsRecord
     */
    public NewsRecord(ch.schlierelacht.admin.jooq.tables.pojos.News value) {
        super(News.NEWS);

        if (value != null) {
            setId(value.getId());
            setDate(value.getDate());
            setTitle(value.getTitle());
            setIntroText(value.getIntroText());
            setFullText(value.getFullText());
            setCloudflareId(value.getCloudflareId());
            setActive(value.getActive());
            resetChangedOnNotNull();
        }
    }
}
