/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.records;


import ch.schlierelacht.admin.jooq.tables.OkMember;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OkMemberRecord extends UpdatableRecordImpl<OkMemberRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.ok_member.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ok_member.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.ok_member.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ok_member.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.ok_member.role</code>.
     */
    public void setRole(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.ok_member.role</code>.
     */
    public String getRole() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.ok_member.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.ok_member.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.ok_member.cloudflare_id</code>.
     */
    public void setCloudflareId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.ok_member.cloudflare_id</code>.
     */
    public String getCloudflareId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.ok_member.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.ok_member.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OkMemberRecord
     */
    public OkMemberRecord() {
        super(OkMember.OK_MEMBER);
    }

    /**
     * Create a detached, initialised OkMemberRecord
     */
    public OkMemberRecord(Long id, String name, String role, String email, String cloudflareId, Integer sortOrder) {
        super(OkMember.OK_MEMBER);

        setId(id);
        setName(name);
        setRole(role);
        setEmail(email);
        setCloudflareId(cloudflareId);
        setSortOrder(sortOrder);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised OkMemberRecord
     */
    public OkMemberRecord(ch.schlierelacht.admin.jooq.tables.pojos.OkMember value) {
        super(OkMember.OK_MEMBER);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setRole(value.getRole());
            setEmail(value.getEmail());
            setCloudflareId(value.getCloudflareId());
            setSortOrder(value.getSortOrder());
            resetTouchedOnNotNull();
        }
    }
}
