/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.records;


import ch.schlierelacht.admin.jooq.enums.OkTeam;
import ch.schlierelacht.admin.jooq.tables.OkTeamMember;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OkTeamMemberRecord extends UpdatableRecordImpl<OkTeamMemberRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.ok_team_member.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ok_team_member.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.ok_team_member.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ok_team_member.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.ok_team_member.team</code>.
     */
    public void setTeam(OkTeam value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.ok_team_member.team</code>.
     */
    public OkTeam getTeam() {
        return (OkTeam) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OkTeamMemberRecord
     */
    public OkTeamMemberRecord() {
        super(OkTeamMember.OK_TEAM_MEMBER);
    }

    /**
     * Create a detached, initialised OkTeamMemberRecord
     */
    public OkTeamMemberRecord(Long id, String name, OkTeam team) {
        super(OkTeamMember.OK_TEAM_MEMBER);

        setId(id);
        setName(name);
        setTeam(team);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised OkTeamMemberRecord
     */
    public OkTeamMemberRecord(ch.schlierelacht.admin.jooq.tables.pojos.OkTeamMember value) {
        super(OkTeamMember.OK_TEAM_MEMBER);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setTeam(value.getTeam());
            resetTouchedOnNotNull();
        }
    }
}
