/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.records;


import ch.schlierelacht.admin.jooq.tables.Programm;

import java.time.LocalDate;
import java.time.LocalTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProgrammRecord extends UpdatableRecordImpl<ProgrammRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.programm.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.programm.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.programm.attraction_id</code>.
     */
    public void setAttractionId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.programm.attraction_id</code>.
     */
    public Long getAttractionId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.programm.location_id</code>.
     */
    public void setLocationId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.programm.location_id</code>.
     */
    public Long getLocationId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.programm.from_date</code>.
     */
    public void setFromDate(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.programm.from_date</code>.
     */
    public LocalDate getFromDate() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>public.programm.from_time</code>.
     */
    public void setFromTime(LocalTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.programm.from_time</code>.
     */
    public LocalTime getFromTime() {
        return (LocalTime) get(4);
    }

    /**
     * Setter for <code>public.programm.to_date</code>.
     */
    public void setToDate(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.programm.to_date</code>.
     */
    public LocalDate getToDate() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>public.programm.to_time</code>.
     */
    public void setToTime(LocalTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.programm.to_time</code>.
     */
    public LocalTime getToTime() {
        return (LocalTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProgrammRecord
     */
    public ProgrammRecord() {
        super(Programm.PROGRAMM);
    }

    /**
     * Create a detached, initialised ProgrammRecord
     */
    public ProgrammRecord(Long id, Long attractionId, Long locationId, LocalDate fromDate, LocalTime fromTime, LocalDate toDate, LocalTime toTime) {
        super(Programm.PROGRAMM);

        setId(id);
        setAttractionId(attractionId);
        setLocationId(locationId);
        setFromDate(fromDate);
        setFromTime(fromTime);
        setToDate(toDate);
        setToTime(toTime);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ProgrammRecord
     */
    public ProgrammRecord(ch.schlierelacht.admin.jooq.tables.pojos.Programm value) {
        super(Programm.PROGRAMM);

        if (value != null) {
            setId(value.getId());
            setAttractionId(value.getAttractionId());
            setLocationId(value.getLocationId());
            setFromDate(value.getFromDate());
            setFromTime(value.getFromTime());
            setToDate(value.getToDate());
            setToTime(value.getToTime());
            resetChangedOnNotNull();
        }
    }
}
