/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.records;


import ch.schlierelacht.admin.jooq.tables.PushDeviceToken;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PushDeviceTokenRecord extends UpdatableRecordImpl<PushDeviceTokenRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.push_device_token.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.push_device_token.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.push_device_token.token</code>.
     */
    public void setToken(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.push_device_token.token</code>.
     */
    public String getToken() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.push_device_token.platform</code>.
     */
    public void setPlatform(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.push_device_token.platform</code>.
     */
    public String getPlatform() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.push_device_token.locale</code>.
     */
    public void setLocale(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.push_device_token.locale</code>.
     */
    public String getLocale() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.push_device_token.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.push_device_token.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.push_device_token.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.push_device_token.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PushDeviceTokenRecord
     */
    public PushDeviceTokenRecord() {
        super(PushDeviceToken.PUSH_DEVICE_TOKEN);
    }

    /**
     * Create a detached, initialised PushDeviceTokenRecord
     */
    public PushDeviceTokenRecord(Long id, String token, String platform, String locale, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(PushDeviceToken.PUSH_DEVICE_TOKEN);

        setId(id);
        setToken(token);
        setPlatform(platform);
        setLocale(locale);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised PushDeviceTokenRecord
     */
    public PushDeviceTokenRecord(ch.schlierelacht.admin.jooq.tables.pojos.PushDeviceToken value) {
        super(PushDeviceToken.PUSH_DEVICE_TOKEN);

        if (value != null) {
            setId(value.getId());
            setToken(value.getToken());
            setPlatform(value.getPlatform());
            setLocale(value.getLocale());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetTouchedOnNotNull();
        }
    }
}
