/*
 * This file is generated by jOOQ.
 */
package ch.schlierelacht.admin.jooq.tables.records;


import ch.schlierelacht.admin.jooq.enums.SponsoringType;
import ch.schlierelacht.admin.jooq.tables.Sponsoring;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SponsoringRecord extends UpdatableRecordImpl<SponsoringRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.sponsoring.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.sponsoring.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.sponsoring.type</code>.
     */
    public void setType(SponsoringType value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.sponsoring.type</code>.
     */
    public SponsoringType getType() {
        return (SponsoringType) get(1);
    }

    /**
     * Setter for <code>public.sponsoring.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.sponsoring.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.sponsoring.cloudflare_id</code>.
     */
    public void setCloudflareId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.sponsoring.cloudflare_id</code>.
     */
    public String getCloudflareId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.sponsoring.url</code>.
     */
    public void setUrl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.sponsoring.url</code>.
     */
    public String getUrl() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SponsoringRecord
     */
    public SponsoringRecord() {
        super(Sponsoring.SPONSORING);
    }

    /**
     * Create a detached, initialised SponsoringRecord
     */
    public SponsoringRecord(Long id, SponsoringType type, String name, String cloudflareId, String url) {
        super(Sponsoring.SPONSORING);

        setId(id);
        setType(type);
        setName(name);
        setCloudflareId(cloudflareId);
        setUrl(url);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised SponsoringRecord
     */
    public SponsoringRecord(ch.schlierelacht.admin.jooq.tables.pojos.Sponsoring value) {
        super(Sponsoring.SPONSORING);

        if (value != null) {
            setId(value.getId());
            setType(value.getType());
            setName(value.getName());
            setCloudflareId(value.getCloudflareId());
            setUrl(value.getUrl());
            resetChangedOnNotNull();
        }
    }
}
